### ISSUE TITLE
UI for Dashboard

### ISSUE THREAD

**Issue by Ratangulati** [Counselllor/Counsellor-Web#1007]
**Describe the bug**
The heading subscribe to our newsletter is small compared to other components.

**To Reproduce**

**Expected behavior**

**Screen
<img width="810" alt="Screenshot 2024-07-13 at 9 38 54 AM" src="https://github.com/user-attachments/assets/17c7d7ec-d27a-4d16-a32a-05640d844d52">
shots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thestarsahil** [comment]
It's okay , don't work on it !
Already done this area
