### ISSUE TITLE
Want to create the dark mode for the jobs page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#1019]
**Is your feature request related to a problem? Please describe.**
I want to create the dark mode for the jobs pages 

![image](https://github.com/user-attachments/assets/dcf0a1e7-bdb1-4444-a469-8128ede338ec)

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i already opened an issue for the same can i work on this

**Comment by thestarsahil** [comment]
First Do the previous work already assigned don't run too fast

**Comment by Ayushmaanagarwal1211** [comment]
Sir actually some of the issues are already fixed by others as this issue is already done by nishant 
so i am closing it
