### ISSUE TITLE
Add CODE OF CONDUCT.md 

### ISSUE THREAD

**Issue by shanvijha30** [Counselllor/Counsellor-Web#102]
The Code oof Conduct will defines standards for how to engage in a community.
File type markdown.

**Comment by shanvijha30** [comment]
@thestarsahil Could you please assign this issue to me under GSSOC ' 23.
I would like to work on it.
Thank you!

**Comment by thestarsahil** [comment]
Go ahead !

**Comment by priyanshu942** [comment]
I'm a GSSoC contributor ..
I would like to work on this section...

would you please assign me to this task ??

**Comment by omkarguravv** [comment]
This issue is already assigned.
You can work on other issues.

**Comment by priyanshu942** [comment]
ok
