### ISSUE TITLE
User Login not working 

### ISSUE THREAD

**Issue by thestarsahil** [Counselllor/Counsellor-Web#1023]
**Describe the bug**
A User try to click , login button not working !

**Screenshots**
![Screenshot from 2024-07-13 16-41-28](https://github.com/user-attachments/assets/96657b0f-2b86-4e8c-ba9b-9e27fe938f2e)

**Comment by Asymtode712** [comment]
Hey @thestarsahil can I fix this??

**Comment by nishant0708** [comment]
I want to @thestarsahil fix this

**Comment by thestarsahil** [comment]
Work in collab

**Comment by Asymtode712** [comment]
Hey @thestarsahil , as @nishant0708 have previously worked on sign up and sign in functionality, I will let him have the issue solved, I will look out for some other issues

Also, thanks for assigning me!!

**Comment by thestarsahil** [comment]
@Asymtode712 We are more focusing on backend part now 
You can try with that !
