### ISSUE TITLE
Make blogs home page

### ISSUE THREAD

**Issue by komal-agarwal5** [Counselllor/Counsellor-Web#1026]
**Is your feature request related to a problem? Please describe.**
I want to design a blog home page

**Describe the solution you'd like**
It will have blogs in cards form designed beautifully

**Describe alternatives you've considered**

**Additional context**
![Screenshot 2024-07-07 151020](https://github.com/user-attachments/assets/11df5649-6b70-4314-905b-64078f9bd8da)
The boxes represent blog cards

**Comment by thestarsahil** [comment]
You can see the latest blog update in project , let me what you can do

**Comment by komal-agarwal5** [comment]
> You can see the latest blog update in project , let me what you can do

Yes I checked its provision is for adding new blogs ie this:
![image](https://github.com/user-attachments/assets/11337437-b8bd-4de3-bf96-49b001b21f1b)

I want to add a blog home page where blogs can be displayed all at once in the form of cards like this
![image](https://github.com/user-attachments/assets/129d8187-f4c4-489a-88ae-6d15311ab18b)
here each box represents a designed card having blog name,small description and image

@thestarsahil

**Comment by thestarsahil** [comment]
@nishant0708 Already raised PR !
If not work you can work on that

**Comment by nishant0708** [comment]
Hey @komal-agarwal5 blog homepage already exists

**Comment by nishant0708** [comment]
See route /blogs

**Comment by nishant0708** [comment]
![image](https://github.com/user-attachments/assets/1f4c9c2b-b889-4abc-8548-e0640dc3c8c7)
it is there just we are facing data storing and fetching issue so working on that

**Comment by thestarsahil** [comment]
![Screenshot from 2024-07-14 18-13-29](https://github.com/user-attachments/assets/bb3db7e8-518a-4f17-8334-4be778217207)

You can work on that 

Public folder -> Pics 
They should be inside the src -> assets

Pages/ Profile 
Whole folder need to been shifted ->  to component section and rename to Profile

**Comment by thestarsahil** [comment]
Raise a PR for that

**Comment by komal-agarwal5** [comment]
> ![Screenshot from 2024-07-14 18-13-29](https://private-user-images.githubusercontent.com/84167034/348550113-bb3db7e8-518a-4f17-8334-4be778217207.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA5Njk5MTAsIm5iZiI6MTcyMDk2OTYxMCwicGF0aCI6Ii84NDE2NzAzNC8zNDg1NTAxMTMtYmIzZGI3ZTgtNTE4YS00ZjE3LTgzMzQtNGJlNzc4MjE3MjA3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE0VDE1MDY1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc3Y2IzNGNhM2ZiMjBhYjk1ZDAzYTc2MDVjMzVlZDYzZDY5MjhjYTdmMDNiMmQzMDgyNWY3NTc5NjA4YjUyNzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.E5CG_StbiPZHOZFSXTdpqsb7iEcV8cYolp6so8HjpzA)
> 
> You can work on that
> 
> Public folder -> Pics They should be inside the src -> assets
> 
> Pages/ Profile Whole folder need to been shifted -> to component section and rename to Profile

Yes i am doing it
