### ISSUE TITLE
Home link in the footer points to login page

### ISSUE THREAD

**Issue by techy4shri** [Counselllor/Counsellor-Web#1037]
**Describe the bug**
The home page should be where you have cards and content telling what this website is about, instead of a login page.

**To Reproduce**
1. Go to 'the website link'
2. Click on 'Home' link in footer
3. See error

**Expected behavior**
The home link should point towards the home page not login pge.

**Screenshots**
![image](https://github.com/user-attachments/assets/487e4be0-6c73-4e5a-9558-b4ccb3f30fca)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Google Chrome

**Smartphone (please complete the following information):**

**Additional context**

**Comment by siddharthbaleja7** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by techy4shri** [comment]
@siddharthbaleja7 you can raise your own issues if you want to work on them Siddhart.
