### ISSUE TITLE
Want to Add Functionality to Like Blogs

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#1044]
![image](https://github.com/user-attachments/assets/808230f8-d1a5-435b-810b-3126e60276ec)
something like this

**Comment by thestarsahil** [comment]
Already you did this

**Comment by nishant0708** [comment]
No it's not there @thestarsahil

**Comment by thestarsahil** [comment]
@nishant0708 Okay 

Also Fix this 

1. Gap in Footer Section 
2. Clicking on card not working user have to click on **read more** button 
3. Refreshing the blog page , blog take a transition of fade in everytime

[Screencast from 2024-07-15 12-07-48.webm](https://github.com/user-attachments/assets/a2a804ba-8657-4c97-a8b9-dfd68a4851ac)

![Screenshot from 2024-07-15 12-07-02](https://github.com/user-attachments/assets/7e7d8f23-be4b-48b6-9609-2a359717d3c9)

**Comment by nishant0708** [comment]
@thestarsahil okay i will please assign it to me
