### ISSUE TITLE
Want to remove this dot from navbar

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#1056]
![image](https://github.com/user-attachments/assets/c36b2625-122e-41e4-93cc-0d3be4c18230)
![image](https://github.com/user-attachments/assets/09c3e2f8-03c7-4316-bac8-d010eacb78c4)

it is redirecting to error page which i guess was for testing purposes but we dont need anymore

**Comment by thestarsahil** [comment]
Already Done
