### ISSUE TITLE
Want to add create job modal to give the form for real time jobs 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#1058]
**Is your feature request related to a problem? Please describe.**
I want to add the modal or the form from which any organization can fill in the details required for that 

![image](https://github.com/user-attachments/assets/6b028566-6e15-4cbf-9cd1-d06a8a168545)

**Comment by thestarsahil** [comment]
Already Done 
Update the branch

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i think you are talking about this modal but this modal is for submitting the application by the candidate but i want to create a modal and then backend for the organizations and connect with database so that they will post the available jobs

https://github.com/user-attachments/assets/b31f77b5-6774-4109-8ab5-e008b2f0d805
