### ISSUE TITLE
Want to write the backend of the Job Application Page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#1059]
**Is your feature request related to a problem? Please describe.**
I want to write the backend of the job application page 
Thorough whihc it can fetch real time data where users can respond to it 

![image](https://github.com/user-attachments/assets/9e3618ee-6ff1-4a40-ae1b-922166c660c3)

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i have created the modal should i start working on that

**Comment by thestarsahil** [comment]
okay

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir to work on that the job modal to be merged but as you say that we have to wait till admin so i 
## Will implement the backend for student details modal like the details will be stored in the database as filled by the user

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil Sir now i am starting working on that
