### ISSUE TITLE
Feature Details of Contributors

### ISSUE THREAD

**Issue by thestarsahil** [Counselllor/Counsellor-Web#1062]
![Fix the gap bw navabar and college section(2)](https://github.com/user-attachments/assets/de4cabb0-f88a-403e-a126-45868fcd5709)

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir can you pelase assign this to me i want to work

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i am starting working on that i know just clear 2 doubts that
- I will  Fetch data from the github like country , working profile social media handles etc. It will show if user linked that 
- Should i updated this card like below the number of contributions

**Comment by thestarsahil** [comment]
Updating card take time , the best to fetch that data
