### ISSUE TITLE
[Feat]  : Create Cources Page

### ISSUE THREAD

**Issue by dhruv8433** [Counselllor/Counsellor-Web#1072]
**Is your feature request related to a problem? Please describe.**

@thestarsahil 

we can add cources route 

![image](https://github.com/user-attachments/assets/4ef3ac78-741c-410f-9f7a-593aef6ddda4)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
alreday there
