### ISSUE TITLE
Redesigning the FAQs section

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#1073]
![image](https://github.com/user-attachments/assets/4e8441ae-193f-41b7-a7c4-ad1b44335e0b)

@thestarsahil a lot has changed after I made this FAQs section
Now I want to add few more details to it

**Comment by thestarsahil** [comment]
I good to look this , no need

**Comment by ayush-848** [comment]
> It's good to look this , no need

That's help section contains a different faq
I thought of merging both here
