### ISSUE TITLE
redesigning the Join-Us page

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#1074]
![image](https://github.com/user-attachments/assets/c2f34f56-5d36-482a-8da7-252865ad791e)

I want to add styling to this page

**Comment by thestarsahil** [comment]
Also Remove the home button

**Comment by ayush-848** [comment]
> Also Remove the home button

What should I give here
An arrow??

**Comment by thestarsahil** [comment]
Nothing
