### ISSUE TITLE
Testimonial Text Color Does Not Change with Theme Toggle.

### ISSUE THREAD

**Issue by siddharthbaleja7** [Counselllor/Counsellor-Web#1075]
### Issue Description
When toggling themes between light and dark mode, the testimonial text color remains unchanged. This issue occurs regardless of the theme toggled, and the testimonial text color does not update accordingly.

### Steps to Reproduce
1. Navigate to the page or component where testimonials are displayed.
2. Toggle the theme from light to dark mode or vice versa.
3. Observe that the testimonial text color does not change as expected.

### Expected Behavior
The testimonial text color should change:
- To white  in dark mode.
- To a darker color  in light mode.

### Actual Behavior
The testimonial text color remains the same color regardless of the theme toggled.

### Environment
- **Browser:** Specify the browser and version.
- **Operating System:** Specify the operating system (e.g., Windows 10, macOS).

### Additional Information
- Include any relevant screenshots or console logs if applicable.

---
<img width="1254" alt="Screenshot 2024-07-16 at 01 12 08" src="https://github.com/user-attachments/assets/6934fdc0-cfd4-4369-96b0-c34c4a2a92c4">

**Comment by siddharthbaleja7** [comment]
@thestarsahil  please assign this issue to me.

**Comment by thestarsahil** [comment]
@nishant0708 He is already working on it
