### ISSUE TITLE
[Feature]: Add dynamic loading of contributors cards

### ISSUE THREAD

**Issue by Asymtode712** [Counselllor/Counsellor-Web#1076]
Currently, we are displaying the contributors cards all in one go

![contri](https://github.com/user-attachments/assets/9a4fe599-2319-42c1-bddd-fb5804256d93)

- Instead, I would initially like to display 4 cards and a load button below them which when clicked will load another 4 cards and so on......

**Comment by Asymtode712** [comment]
@thestarsahil Please assign me this issue

**Comment by thestarsahil** [comment]
Not necessary , this is all good

**Comment by Asymtode712** [comment]
@thestarsahil Ok no problem
