### ISSUE TITLE
CSS Layout Issue in Contact Form

### ISSUE THREAD

**Issue by siddharthbaleja7** [Counselllor/Counsellor-Web#1092]
### Description
There is a CSS layout issue with the Contact Form on the main page. The form elements are not aligned properly, and the layout does not look correct.

### Steps to Reproduce
1. Go to the main page.
2. Scroll down to the Contact section.
3. Observe the alignment and layout of the form elements.

### Expected Behavior
The form elements should be properly aligned, and the layout should be visually appealing.

### Screenshots
<img width="1463" alt="Screenshot 2024-07-16 at 20 54 53" src="https://github.com/user-attachments/assets/99d75ada-9c7a-4120-916e-d36d1feace37">

### Browser Information
- Browser: Chrome
- Version: 91.0.4472.124
- Operating System: macOS Big Sur

### Additional Information
Any additional information that might be helpful in diagnosing the issue.

### Possible Solutions
Describe any potential solutions you have in mind. For example:
- Adjust the CSS properties for the form elements.
- Use a flexbox or grid layout to align the form elements properly.

**Comment by siddharthbaleja7** [comment]
Can you please assign this issue to me?

**Comment by thestarsahil** [comment]
update your branch
