### ISSUE TITLE
Form is not properly spaced.

### ISSUE THREAD

**Issue by pahuja-sahil** [Counselllor/Counsellor-Web#1104]
On carreer support page the  form under "Get Personalized advice" is not spaced properly. There is no spacing on the right of the form.
Image:

![image](https://github.com/user-attachments/assets/93c69ee7-7a7f-4596-9e43-a59728f2ff13)

I would like to fix this issue under gssoc 24.
Thank you.

**Comment by ayush-848** [comment]
> @ayush-848 kindly assign this issue to me under gssoc.

This is not my project, tag @thestarsahil

**Comment by pahuja-sahil** [comment]
> > @ayush-848 kindly assign this issue to me under gssoc.
> 
> This is not my project, tag @thestarsahil

mb , i'll do that.

**Comment by pahuja-sahil** [comment]
@thestarsahil  kindly assign this issue to me under gssoc.

**Comment by thestarsahil** [comment]
@pahuja-sahil this year project contributors spaced full , try next year 
Thanks !
