### ISSUE TITLE
Want to fix the dark mode for the blog reading page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#1121]
**Is your feature request related to a problem? Please describe.**
I want to fix the Dark mode of the blog reading page as it is not optimized for blog reading page

![image](https://github.com/user-attachments/assets/aea149a6-eb8e-43f2-bd78-3466bfa5a1e3)

**Comment by thestarsahil** [comment]
It's done
