### ISSUE TITLE
Bug: Implementing Word Limit while creating blogs

### ISSUE THREAD

**Issue by Kiran-pande-30** [Counselllor/Counsellor-Web#1129]
**Describe the bug**
Currently, We can create with one single space OR a single word.

**To Reproduce**
1. Go to 'Blogs'
2. Click on 'create blog'
3. Type space in every field " Title Content Tags"

**Expected behavior**
We should implement some words limit for the title, description and tags.

**Screenshots**
[

https://github.com/user-attachments/assets/e170f495-95dd-4eb6-b99b-0ffd6458c708

](url)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 

**Additional context**
Please also specify the word limit

**Comment by siddharthbaleja7** [comment]
@thestarsahil  Can you please assign this issue to me?

**Comment by Kiran-pande-30** [comment]
@siddharthbaleja7 I have raised the issue and will also work on it.

**Comment by thestarsahil** [comment]
@Kiran-pande-30 Sorry but the space for contributor full !
You can try next year !
We are ready to welcome you !
Thanks Happy Coding

**Comment by Kiran-pande-30** [comment]
@thestarsahil is there any restrictions on no.  of contribuors
