### ISSUE TITLE
Other Then Login Page Toast are Not Working

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#1133]
toast are not working On Rest of pages

**Comment by thestarsahil** [comment]
can you please elaborate

**Comment by nishant0708** [comment]
See the code of blog or any other page there is toast code but it is not working

**Comment by thestarsahil** [comment]
But it is  not required

**Comment by nishant0708** [comment]
@thestarsahil  Like that are toast it like if I created article it's good if I receive notification that article is created
