### ISSUE TITLE
Profile page is not accessible

### ISSUE THREAD

**Issue by anwesha2002** [Counselllor/Counsellor-Web#1144]
**Describe the bug**
Profile page is not working as it has a bug

**To Reproduce**
1. Go to 'https://counsellor.social/dashboard'
2. Click on 'profile'
3. See error

**Expected behavior**
It should work 

**Screenshots**
![Screenshot 2024-07-20 052425](https://github.com/user-attachments/assets/12f12bad-68d7-407e-ab90-0a38259d06e4)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
i am gssoc'24 contributor @thestarsahil  please assign this to me

**Comment by thestarsahil** [comment]
Link broken fix it

**Comment by razerbotog** [comment]
@thestarsahil I also raised a PR for this issue.  #1242
