### ISSUE TITLE
[Bug] : On Logo click redirect back to home 

### ISSUE THREAD

**Issue by dhruv8433** [Counselllor/Counsellor-Web#1170]
**Describe the bug**

@thestarsahil 

when user click on logo it can redirected to home route

**To Reproduce**
1. Go to 'navigation'
2. click on logg

**Expected behavior**

**Screenshots**
![image](https://github.com/user-attachments/assets/1dc043b3-5d22-41a9-9333-ef776664e720)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thestarsahil** [comment]
It is working
