### ISSUE TITLE
[Bug] : When we visit profile page it have some errors 

### ISSUE THREAD

**Issue by dhruv8433** [Counselllor/Counsellor-Web#1171]
**Describe the bug**

@thestarsahil 

check this out,
when i try to visit `/profile` route 
i got 

![image](https://github.com/user-attachments/assets/c6d0ecde-97cf-42ea-8ad8-0d7be7f9027b)

**Expected behavior**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thestarsahil** [comment]
Done
