### ISSUE TITLE
[Feature] About Section 

### ISSUE THREAD

**Issue by parthpathakpp1** [Counselllor/Counsellor-Web#12]
There is no about us section . Will make about section .

**Requirements**-:
1.Something about you which I can write in the section .

![COUNSELLOR ABOUT](https://github.com/thestarsahil/Counsellor/assets/85991449/a34cce9e-65af-4811-9806-97949ec267fb)

**Comment by parthpathakpp1** [comment]
Assign this issue to me under GSSOC'23.

**Comment by Joban69** [comment]
![Screenshot (64)](https://github.com/thestarsahil/Counsellor/assets/89921178/f9a70a3a-6e5b-4d88-aebd-2d3b4b3e18d1)
there is lot of work to do in about section. will i give my contribution to this section
