### ISSUE TITLE
sign up page is too constricted and css is not good.

### ISSUE THREAD

**Issue by ePSA-eJya** [Counselllor/Counsellor-Web#121]
**Describe the bug**
the space is too less in between .

**Expected behavior**
more spacing

**Screenshots**
![image](https://github.com/thestarsahil/Counsellor/assets/120899038/bb6cddc9-8ce9-4ef6-ac05-491a84b05e1b)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thestarsahil** [comment]
#113 #123  
Please Check out this

**Comment by ePSA-eJya** [comment]
It's been fixed i guess.
