### ISSUE TITLE
Updation of Readme.md file

### ISSUE THREAD

**Issue by Anjaliavv51** [Counselllor/Counsellor-Web#1229]
Readme.md is not of latest changes of the webpage.

![image](https://github.com/user-attachments/assets/134db38d-a6ec-48c7-ae48-2a809ea79aa4)

**Comment by Anjaliavv51** [comment]
@thestarsahil please assign me this issue.

**Comment by thestarsahil** [comment]
Dear you are late , next year apply First Come First Serve !
See you soon next year !
