### ISSUE TITLE
Upgrading the Edit profile section 

### ISSUE THREAD

**Issue by thestarsahil** [Counselllor/Counsellor-Web#1252]
![Fix the gap bw navabar and college section(10)](https://github.com/user-attachments/assets/14cb3436-00d7-4a5e-93fa-601b3f94a846)

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Can i work on it

**Comment by thestarsahil** [comment]
You have assigned already too much , First Complete that you assigned

**Comment by Ayushmaanagarwal1211** [comment]
@thestarsahil  Sir i already raised a pr for all those

**Comment by Ayushmaanagarwal1211** [comment]
and one of them include the job modal backend integration so that can't be done without merging modal pr sir so i am waiting for that

**Comment by Ayushmaanagarwal1211** [comment]
> You have assigned already too much , First Complete that you assigned

and sir i will surely complete this by today if not you can assign it to anyone else i have no problem with that

**Comment by Ayushmaanagarwal1211** [comment]
Thank you sir i will surely raise pr for this today
