### ISSUE TITLE
Enhancing the terms and conditions page

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#1253]
To give it a proper layout and styling

**Comment by ayush-848** [comment]
@thestarsahil please assign this issue to me

**Comment by ayush-848** [comment]
@thestarsahil should I remove the home button??

**Comment by thestarsahil** [comment]
Yes

**Comment by ayush-848** [comment]
> Yes

@thestarsahil I have issued the PR please check it
