### ISSUE TITLE
Parts of join us page are not readable in light mode

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#1268]
Parts of join us page are not readable in light mode

![image](https://github.com/user-attachments/assets/4658b505-a8a7-4c95-9d6e-d836697ef03a)
![image](https://github.com/user-attachments/assets/a80eda4f-ddc4-4d75-9348-eb28d4033d0a)

**Comment by ayush-848** [comment]
@thestarsahil also wrong color and font family for the h1, h2 and h3 headings

![image](https://github.com/user-attachments/assets/10bec842-6db7-420c-8c0e-de7d33322e84)

**Comment by thestarsahil** [comment]
Do as same as privacy page , font size should be same as 
Reference for font size : Top University Page

**Comment by ayush-848** [comment]
> Do as same as privacy page , font size should be same as Reference for font size : Top University Page

Sure kindly assign this to me

**Comment by ayush-848** [comment]
@thestarsahil i wanted to create a new pr
after I created a new branch all the pages are showing firebase errors

**Comment by ayush-848** [comment]
@thestarsahil in which folder should I create the .encv file

**Comment by thestarsahil** [comment]
Why to need this .env in this join us page ?

**Comment by ayush-848** [comment]
> Why to need this .env in this join us page ?

After I made the changes I created a new branch 
When I run it, the pages were giving error due to firebase/auth do not exists

**Comment by ayush-848** [comment]
@thestarsahil 
![image](https://github.com/user-attachments/assets/d4bc60c9-642d-4b6a-9eb1-60385df5f3d6)

**Comment by ayush-848** [comment]
@thestarsahil I have fixed it. I need to discuss it with you. Please before that do not merge any other PR

**Comment by thestarsahil** [comment]
Due to auth file Missing 
Now check

**Comment by ayush-848** [comment]
@thestarsahil what other styling issues needs to be fixed??
