### ISSUE TITLE
Fonts and colors of some part of Top University page is not matching

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#1290]
![image](https://github.com/user-attachments/assets/5c704c72-f9a1-4098-b496-562a22547084)
![image](https://github.com/user-attachments/assets/025c4f53-9ad8-4da1-99b5-e8f284b29606)

**Comment by ayush-848** [comment]
@thestarsahil please check this

**Comment by ayush-848** [comment]
@thestarsahil please add the gssoc level to #1281

**Comment by thestarsahil** [comment]
done
