### ISSUE TITLE
Course link brokeage

### ISSUE THREAD

**Issue by thestarsahil** [Counselllor/Counsellor-Web#1301]
Localhost , the image path are corrected and showing all images ( Working ) 
![Screenshot from 2024-07-29 19-48-13](https://github.com/user-attachments/assets/532dc2ff-44f6-4203-8e1a-a579890e374c)

Live Server , the image path are not corrected and not showing all images ( Not Working ) 

![Screenshot from 2024-07-29 19-48-20](https://github.com/user-attachments/assets/8cc3a9e3-c123-4b06-9bde-aa0313cb6307)

**Comment by nishant0708** [comment]
Hey @thestarsahil can I work on this?

**Comment by abhinavjha0239** [comment]
Hello, @thestarsahil, could you please assign this issue to me? I’m excited to work on it and would like to get started promptly.
