### ISSUE TITLE
Want to Write Backend Of Post Jobs and retrieve jobs from backend to frontend

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#1314]
![image](https://github.com/user-attachments/assets/4baf65c2-9e76-4a38-97bb-ddc235a82111)

**Comment by Ayushmaanagarwal1211** [comment]
@nishant0708 sorry bro actually i already created that issue two weeks ago but sir didn't merged my jobs pr so i was unable to do that but now he merged that and i can do that

**Comment by thestarsahil** [comment]
@nishant0708 Do apply job integration and show candidate successfully filled 
The job post Consultant get the data those candidate applied for job

**Comment by thestarsahil** [comment]
Make a NEW issue for that
