### ISSUE TITLE
Add Icons to Navbar 

### ISSUE THREAD

**Issue by sailaja-adapa** [Counselllor/Counsellor-Web#1326]
Hello Project Admin
I would like to add icons to Navbar
Can you assign me this issue under GSSOC'24 @thestarsahil 

![IMG_20240731_153516](https://github.com/user-attachments/assets/9bab8bd7-b168-4c62-af93-d0eb3ee9903b)

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @thestarsahil

**Comment by VinayakPaka** [comment]
Can you please assign it to me.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsssoc-ext and hacktoberfest.. level 3 label
