### ISSUE TITLE
Add a Rate Us Option 

### ISSUE THREAD

**Issue by sailaja-adapa** [Counselllor/Counsellor-Web#1327]
Hello, my name is A.A.D.Sailaja. I am a Tech Enthusiastic and i'm looking forward to contribute in open source projects. Here in this project i would like to add a rate us option it will allow the user to rate our website and also he can suggest us to improve if any 

Can you please assign me this issue under gssoc'24 @thestarsahil

**Comment by sailaja-adapa** [comment]
Can you assign me this issue under GSSOC'24 @thestarsahil

**Comment by VinayakPaka** [comment]
Can you assign it to me? I will solve this!

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsssoc-ext and hacktoberfest.. level 3 label
