### ISSUE TITLE
Add alternate Image on Error

### ISSUE THREAD

**Issue by DevGajjar28** [Counselllor/Counsellor-Web#1330]
**Is your feature request related to a problem? Please describe.**
So currently at Courses page, images are not showing because of some error on network side or not in media.

**Describe the solution you'd like**
i would like to add an alternate image on error if image not find.  It will show alternate image if main image of the page not found. So user don't have to face and any problems on website.  

**Describe alternatives you've considered**

**Additional context**
Here i have provided error Photo
![image](https://github.com/user-attachments/assets/266ffe7a-06c5-4586-849f-d0a1ccc64e5d)

**Comment by VinayakPaka** [comment]
I want to work on this

**Comment by thestarsahil** [comment]
Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards !
