### ISSUE TITLE
Enhanve the card ui on homepage

### ISSUE THREAD

**Issue by zzzzshawn** [Counselllor/Counsellor-Web#1333]
update the ui for cards displaying institutions to look for captivating and mordern as the current one look bad
![Screenshot (85)](https://github.com/user-attachments/assets/6771e043-c4d2-4501-a00c-361ff646c12a)

**Comment by thestarsahil** [comment]
Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards !
