### ISSUE TITLE
fix ui for student profile

### ISSUE THREAD

**Issue by zzzzshawn** [Counselllor/Counsellor-Web#1334]
**Describe the bug**
the text in student profile is dark which makes it hard to see and profile of student doesn not render

**To Reproduce**
1. Go to 'https://counsellor.social/student/2/Shivam'
2. See error

**Expected behavior**
the text should be properly visible and the profile photo of student needs to be rendered

**Screenshots**

![Screenshot (87)](https://github.com/user-attachments/assets/69d7bbef-ff0d-4685-9d60-25afee3971f4)

**Desktop (please complete the following information):**
 - OS: [windows]
 - Browser [chrome,]
 - 
**Smartphone (please complete the following information):**

**Additional context**

**Comment by Suswetha6** [comment]
hey @thestarsahil ,please assign me this issue

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsssoc-ext and hacktoberfest.. level 3 label

**Comment by thestarsahil** [comment]
not ui , we are looking for data representation on Student Profile 
Is that possible ?

**Comment by SaanyaGarg5** [comment]
> not ui , we are looking for data representation on Student Profile Is that possible ?

yes can do that...

**Comment by thestarsahil** [comment]
Join the Discord channel to get more update regarding this 
Channel name  ; Counsellor

**Comment by thestarsahil** [comment]
you will see in the Gssoc server

**Comment by thestarsahil** [comment]
have you joined the discord channel of gssoc server?

**Comment by SaanyaGarg5** [comment]
Yes

**Comment by thestarsahil** [comment]
@SaanyaGarg5 create a new issue 

Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards  ui part !
