### ISSUE TITLE
Change Text Inside Dark / Light Mode button

### ISSUE THREAD

**Issue by Naveenkumar30838** [Counselllor/Counsellor-Web#1344]
![image](https://github.com/user-attachments/assets/fed59e30-b058-48cc-ac61-1a86af91d829)
On the login Page it shows the text for changing the theme in reverse order . When the page is light mode it asks for light Mode and in dark mode it asks for dark mode , obviously which don't make any sense . Instead in light Mode it should ask for dark mode vice versa.

**Comment by Naveenkumar30838** [comment]
I can fix this and want to work on this issue

**Comment by VinayakPaka** [comment]
I want to work on this

**Comment by thestarsahil** [comment]
Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards !
