### ISSUE TITLE
modify : fix color scheme => dark mode colors are too vibrant fix color scheme

### ISSUE THREAD

**Issue by Riteshkrdivedi** [Counselllor/Counsellor-Web#1354]
in dark mode colors are so harsh for instance compare the dark mode colors of github and your website . A modern touch is needed in dark mode 

![Screenshot 2024-08-20 124810](https://github.com/user-attachments/assets/a7c9e4e6-3b2b-4f9c-b711-f56a79683cd0)

**Comment by Suhas-Koheda** [comment]
Hey I would like to work on this under GSSOC'24 extd and hacktoberfest'24.
can you assign this to me

**Comment by thestarsahil** [comment]
Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards !
