### ISSUE TITLE
Designing "Find your Dream College" Page

### ISSUE THREAD

**Issue by sumitkr2000** [Counselllor/Counsellor-Web#136]
**Is your feature request related to a problem? Please describe.**
Hey @thestarsahil I want to design the find your dream college page and add it to your website. Please assign me this issue. Thank you!

**Describe the solution you'd like**
Designing the find your dream college page

**Describe alternatives you've considered**

**Additional context**

**Comment by VGandhi27** [comment]
Thank you for your concern. Please provide us with a brief description of this issue #136 and how will you make the changes

**Comment by sumitkr2000** [comment]
I want to design the fronted of that page.

**Comment by Harikaraja** [comment]
Can anyone help me how to clone this project in local repository because I was not able to run the project , i have followed the steps  given in Readme.md file but I was not able to even signup or login

**Comment by sumitkr2000** [comment]
@VGandhi27 @thestarsahil Please assign me this issue
