### ISSUE TITLE
Firebase Authentication

### ISSUE THREAD

**Issue by riyaaryan2004** [Counselllor/Counsellor-Web#1389]
**Description**
There is no option for login/signup via google.

**Expected Behavior**
user don't have to enter email and password everytime they visit the website.
user can login without password if their registered gmail account is already logged in their device.

**Solution**
I want to add google firebase authentication.

**Screenshots**
![Screenshot 2024-10-01 205542](https://github.com/user-attachments/assets/e8837d1c-5d1b-4f3d-b211-25076fe8e15b)

![Screenshot 2024-10-01 205644](https://github.com/user-attachments/assets/d033b885-1c2d-49ad-adc2-67f439ddf57e)

**Comment by thestarsahil** [comment]
Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards !
