### ISSUE TITLE
[Feature]: I can improve "Home Page"  UI

### ISSUE THREAD

**Issue by iarmaanx** [Counselllor/Counsellor-Web#1393]
![Screenshot 2024-10-06 214409](https://github.com/user-attachments/assets/aa493ebc-d49a-4a22-b317-f15c3997c24f)

**Describe the solution you'd like**
I can use more appealing visuals.

I'm willing to work on this issue. Please assign this issue to me and add label gssoc-extd and hacktoberfest-accepted to it.

**Comment by SaanyaGarg5** [comment]
you can assign that task to me under gsssoc-ext and hacktoberfest.. level 3 label

**Comment by thestarsahil** [comment]
Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards !
