### ISSUE TITLE
UI Update for the Login Page

### ISSUE THREAD

**Issue by NK-Works** [Counselllor/Counsellor-Web#1399]
I want to update hte ui for the login page as currently the ui is not very good.
![image](https://github.com/user-attachments/assets/75830c04-f879-4ee2-8962-14c2a7c581f1)
make sure to add the labels...
thanks:)

**Comment by thestarsahil** [comment]
Right Now We are accepting, only backend issues
Thanks for issuing but we are not proceeding towards !
