### ISSUE TITLE
update the card ui present in home page with animations and college details page 

### ISSUE THREAD

**Issue by Ayush03K** [Counselllor/Counsellor-Web#1400]
I want to update the card ui present in the home page in to more animate way and also update the college details page ui 
![Screenshot 2024-10-11 090149](https://github.com/user-attachments/assets/f0a5f46e-c766-40e2-99cc-d24eece8fd97)
![Screenshot 2024-10-11 090241](https://github.com/user-attachments/assets/0432a4a7-fdda-4209-ac42-f41e84fb2663)

**Comment by thestarsahil** [comment]
Right Now , we are accepting only backend issues 
Thanks for creating issue but we are not proceeding towards
