### ISSUE TITLE
[FIX]: Update Signup Page

### ISSUE THREAD

**Issue by omkarguravv** [Counselllor/Counsellor-Web#145]
### Issue Description:
We need to update the signup page to improve user experience and increase conversion rates. This issue serves as a tracker for all the tasks related to the signup page update.

### New Design 

![9](https://github.com/Counselllor/Counsellor-Web/assets/89473596/cd5904e8-316f-4ae9-b457-224dd8f8bb80)

![11](https://github.com/Counselllor/Counsellor-Web/assets/89473596/5cb4f394-4c90-48e7-8935-916031f9238e)

**Comment by sumitkr2000** [comment]
Can I work on this issue?

**Comment by VGandhi27** [comment]
In this, we also need to resolve the Cors update issue when we're trying to link client requests with the server

**Comment by sumitkr2000** [comment]
So I have to make the frontend or backend or both??

**Comment by omkarguravv** [comment]
This issue is about the Frontend So for now work on frontend part and backend connections should not be changed.

**Comment by sumitkr2000** [comment]
Okay @omkarguravv
