### ISSUE TITLE
fix: Signup page UI

### ISSUE THREAD

**Issue by SINJINI-G** [Counselllor/Counsellor-Web#149]
Hi @thestarsahil !!

I can fix the signup page UI.. can you please assign this issue to me for gssoc?

**Comment by thestarsahil** [comment]
Have you previously worked on Andriod projects ?
I have something special project for you

**Comment by SINJINI-G** [comment]
> Have you previously worked on Andriod projects ? I have something special project for you

Right now, I am focusing on gssoc.. since in the past you have asked me to contribute as an ui/ux designer in this project, I am creating these issues. Kindly assign them to me so that I can make the UI better.

**Comment by thestarsahil** [comment]
Thank you for your suggestion. It's important to have effective communication channels to keep everyone updated on the progress and next steps in UI development. To ensure seamless collaboration, we will establish both a Slack channel and a Discord channel.
