### ISSUE TITLE
Want to enhance signup form

### ISSUE THREAD

**Issue by DeveloperAshish8** [Counselllor/Counsellor-Web#16]
The current signup form UI seems very annoying , want to enhance it to improve user experience.

![Screenshot (61)](https://github.com/thestarsahil/Counsellor/assets/90233808/a7f2a2d6-60b8-4dfe-8f96-083bf0aacd20)

Please assign me this issue under GSSoC @thestarsahil

**Comment by thestarsahil** [comment]
Hello @DeveloperAshish8 

Thank you for expressing your concern about the current UI of the signup form and your willingness to enhance it to improve the user experience. I appreciate your initiative in making the signup process more user-friendly.

To better understand your vision for the enhanced UI, could you please provide more details or specific ideas on how you would like to improve the signup form? It would be helpful to know the aspects you find annoying and any suggestions you have in mind for a better user experience.

Once I have a clearer understanding of your proposed changes, I will be able to assess their feasibility and discuss further steps with you.

Thank you for your dedication to improving the project's UI, and I look forward to hearing your ideas.

**Comment by DeveloperAshish8** [comment]
I think the heading(Signup) should be more attractive that could be bold and we should have a background gif in the form section so that it would be more eye catching.

**Comment by thestarsahil** [comment]
That's a great suggestion! Making the heading (Signup) more attractive by using a bold font can certainly draw more attention. Additionally, Before that Moving I would know how it would look 
Represent the Ui First

**Comment by DeveloperAshish8** [comment]
Ok let me share an screenshot of the ui

**Comment by KamalSritha-04** [comment]
Can i please get assigned to this issue under GSSOC'23?

**Comment by nishant0708** [comment]
assign me this issue under gssoc24

**Comment by Vinaysohaliya** [comment]
assign me this issue under gssoc24
