### ISSUE TITLE
Adding show password button in Register page

### ISSUE THREAD

**Issue by SubhamB2003** [Counselllor/Counsellor-Web#170]
@thestarsahil Hey, I want to add a show password button on the register page.

Please assign it to me under GSSOC'23. I want to add this.

**Comment by Atharva-Nimbalkar** [comment]
Hi @SubhamB2003, I'm reaching out to express my interest in contributing to the project, specifically regarding the issue "Adding show password button in Register page" (#170).
 
on the register page before: 
![before](https://github.com/Counselllor/Counsellor-Web/assets/113286938/4700ab50-14dd-4d84-80ec-dac509444218)

after :

![after](https://github.com/Counselllor/Counsellor-Web/assets/113286938/00f03585-f4f8-44b8-9f55-808fb9d033a5)

Thank you for considering my request. I look forward to your response and the opportunity to make a meaningful contribution to the project.

Best regards,
atharva nimbalkar
