### ISSUE TITLE
Table Of Contents Missing in the ReadMe ⬇️

### ISSUE THREAD

**Issue by arcVaishali** [Counselllor/Counsellor-Web#189]
### Details
# ISSUE
For better user readability and easy access, it is necessary to add a table of contents at the top of the ReadMe.

I have contributed in documentations in the past, hence, I can resolve this issue in time. **@thestarsahil** Kindly assign me this issue under **GSSoC'23 tag.**

# Screenshots
### Sample ---

<img width="559" alt="table-of-contents" src="https://github.com/Counselllor/Counsellor-Web/assets/98754461/bc715a0e-1fd1-4de7-b80c-079b4024db6d">

**Comment by arcVaishali** [comment]
**@thestarsahil** Kindly assign me this issue under GSSoC'23 tag.

**Comment by thestarsahil** [comment]
Go ahead !
