### ISSUE TITLE
Login with google not working

### ISSUE THREAD

**Issue by deepshikha2708** [Counselllor/Counsellor-Web#199]
**Describe the bug**
Login with google not working

**To Reproduce**
click on login with google
select the google account
login

[x] I agree to follow this project's Code of Conduct 
[x] I'm a GSSoC'23 contributor
[x] I want to work on this issue

**Comment by karantec** [comment]
Please assign me issue. I work on it under GSSOC 2023

**Comment by thestarsahil** [comment]
Make a new PR with New issue !
