### ISSUE TITLE
Make the about page

### ISSUE THREAD

**Issue by Navjot4** [Counselllor/Counsellor-Web#20]
The about page contains nothing,so I want to contribute to it.
Please assign me this issue in gssoc'23.

**Comment by Aditi323** [comment]
Could you please assign me this project as a GSSOC Contributor.

**Comment by thestarsahil** [comment]
We kindly request that you ensure all updates and important information are shared on both our Discord and Slack servers. These communication channels serve as valuable platforms for staying connected, collaborating, and keeping everyone informed about ongoing projects and developments.

If you haven't joined already, we highly encourage you to join our Discord and Slack servers to get firsthand updates on what's happening within the team. It's a great way to stay in the loop, participate in discussions, ask questions, and contribute to the overall progress of our projects.
