### ISSUE TITLE
Bug: Inconsistent Radio Button Names in Sign-up Page

### ISSUE THREAD

**Issue by ChavvaNarayana** [Counselllor/Counsellor-Web#201]
**Describe the bug**
The sign-up page currently allows users to select both the "Student" and "Counsellor" options simultaneously. However, according to the requirements, only one option should be selectable at a time.

**To Reproduce**
1. Navigate to the sign-up page.
2. Observe the "Are you a Student or Counsellor?" section.
3. Attempt to select both the "Student" and "Counsellor" options simultaneously.

**Expected Behavior**
Only one radio button should be selectable at a time. Selecting one option should automatically deselect the other.

**Actual Behavior**
Both the "Student" and "Counsellor" options can be selected simultaneously.

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/98675264/8022a66b-12e5-4de5-9405-643796444f2a)

**Proposed Solution**

- Update the name attribute for both radio buttons to a common value (e.g., "occupation").
- Ensure that the name attributes for both radio buttons are identical.

**Comment by ChavvaNarayana** [comment]
Please assign it to me.

**Comment by thestarsahil** [comment]
go ahead !

**Comment by thestarsahil** [comment]
Fixed !
