### ISSUE TITLE
Login with google in sign up page

### ISSUE THREAD

**Issue by shraddha761** [Counselllor/Counsellor-Web#219]
**Is your feature request related to a problem? Please describe.**
There is no login with google option in sign up page  and also login with google button in sign in page is not working

![image](https://github.com/Counselllor/Counsellor-Web/assets/106100728/e1f60006-2033-4ace-b71b-10266e77779f)

Assign this issue to me under GSSOC'23

**Comment by thestarsahil** [comment]
Make a PR for new Issue
