### ISSUE TITLE
Add hover effects and links to the navbar and improve it

### ISSUE THREAD

**Issue by akanksha984** [Counselllor/Counsellor-Web#220]
I would like to add link to the icon for redirecting and also i would like to add hover effects to the links
Please assign it to me under gssoc'23

![image](https://github.com/Counselllor/Counsellor-Web/assets/97845909/1359b021-f1a9-4517-874d-dbae6d22afa0)

**Comment by sakshimaluskar2** [comment]
I would like to add hover effect and link to the navbar so It can be more User friendly. 
By adding this issue User can use system easily.
Please Assign me this issue under GSSoC'23.

**Comment by thestarsahil** [comment]
Make new PR for new issue !
