### ISSUE TITLE
About Page

### ISSUE THREAD

**Issue by 24-Aarushi-Singh-24** [Counselllor/Counsellor-Web#221]
**Is your feature request related to a problem? Please describe.**
Adding details in the about page and making it properly.
**Describe the solution you'd like**
We could add a description about what the app is and put it on the homepage itself to make it easier.
**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
Go ahead ! Make sure to describe all neccessary stuff 
**Note**  = Update on latest branch

**Comment by JiyaGupta-cs** [comment]
@thestarsahil Please assign me this under IWOC
I will make an About Page corresponding to the current UI of the website

**Comment by JiyaGupta-cs** [comment]
@thestarsahil Please remove the other assignee so that I can get my points

**Comment by thestarsahil** [comment]
Sorry for the inconvience
