### ISSUE TITLE
Inline Validation in Login And signup

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Counselllor/Counsellor-Web#222]
**Is your feature request related to a problem? Please describe.**
yes, There is no validation system in the login and signup form, which can lead to the submission of invalid data.

**Describe the solution you'd like**
I want to implement inline validation for each field in the login and signup form. Also, there are no constraints for fields in the frontend, I want to implement the following constraints :
Name: Min 6 characters
Email: Valid Regex
Password: Min 8 characters with at least 1 uppercase, 1 lowercase,1 symbol, and 1 digit. 

**Sample Video**
I want to implement functionality similar to the below video:

https://github.com/agamjotsingh18/pollitup/assets/86224794/b3d8c27f-da3b-4b82-9ea2-e4db3c710923

**Request**
Please assign me this issue under gssoc23 label.

**Comment by AlfiyaSiddique** [comment]
@thestarsahil can you please review this issue as well!!  Implementing this feature will also be helpful in order to get valid data through  forms.

**Comment by thestarsahil** [comment]
Go ahead !
