### ISSUE TITLE
Enhancement: Sign Up (GSSoC'23)

### ISSUE THREAD

**Issue by abrehan2** [Counselllor/Counsellor-Web#224]
**Is your feature request related to a problem? Please describe.**
I will enhance the sign up page by making it responsive. I will also utilize Chakra UI to change the layout of the page by using it's components. I will replace the current fields with more optimized components.

![image](https://github.com/Counselllor/Counsellor-Web/assets/100872683/b938ebff-66d9-4810-85a3-817455d5493c)

**Comment by thestarsahil** [comment]
Go ahead !

**Comment by abrehan2** [comment]
Please don't forget to add gssoc labels so that the contribution gets counted. Thanks.
