### ISSUE TITLE
Add firebase authentication to the project

### ISSUE THREAD

**Issue by sumitkr2000** [Counselllor/Counsellor-Web#229]
**Is your feature request related to a problem? Please describe.**

Hey @thestarsahil  I want to add Firebase authentication to the login and signup page. Please assign me this issue. Thank you!

**Describe the solution you'd like**

Use firebase to login and signup the user.

**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
Go ahead
