### ISSUE TITLE
Responsive Design Issue - Ensuring Proper Functionality on Tablets, Phones, and Desktop

### ISSUE THREAD

**Issue by thestarsahil** [Counselllor/Counsellor-Web#23]
Currently, the project lacks proper responsiveness across different devices, including tablets, phones, and desktops. It is crucial to address this issue to enhance user experience and ensure consistent functionality across all platforms.

![Counsellor-Portal](https://github.com/thestarsahil/Counsellor/assets/84167034/45671b13-04cd-47a4-a651-45576b6b3325)

The objective of this issue is to implement responsive design principles and make necessary adjustments to the existing codebase to achieve optimal performance on various screen sizes. This includes:

Reviewing the current layout and identifying elements that do not adapt well to different devices.
Making adjustments to CSS styles, media queries, and layout structures to create a responsive design that adapts fluidly to different screen sizes.
Testing the responsiveness of the website/application on multiple devices and resolutions to ensure proper functionality and visual presentation.
Addressing any specific issues or bugs that may arise during the implementation of responsive design.

This issue is open for discussion, and we welcome suggestions and collaboration from the community to ensure the best outcome. Let's work together to create a responsive and user-centric project!

Feel free to ask any questions or provide additional information related to this issue
 Let's make our project responsive and accessible to all users!

**Comment by abhi03ruchi** [comment]
Please assign this task of responsiveness to me. I am well versed with html , css and javascript. 



- Currently, the navbar is also not responsive, it squeezes and does not look pleasant. So I would like to fix this issue and .
Sample:- 

https://github.com/thestarsahil/Counsellor/assets/105661636/2279c7b5-bf08-4247-b2ce-e9218297c5aa



- fix other components which are not responsive.

**Comment by villAsh** [comment]
I can make this responsive please assign this to me under gssoc'23
