### ISSUE TITLE
Add Captcha feature

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Counselllor/Counsellor-Web#235]
**Is your feature request related to a problem? Please describe.**
No

 **Feature** 
I want to implement Captcha functionality in the signup and login form. The aim of CAPTCHA is to differentiate between human users and automated bots, hence it is an important field in such forms. I would implement a text captcha.

 **Request** 
If you find this issue worth implementing then Please assign me this issue under gssoc23.

**Comment by thestarsahil** [comment]
Go ahead !
