### ISSUE TITLE
[BUG] During signup(without google) , the user can select both student and counsellor simultaneously

### ISSUE THREAD

**Issue by Sch476** [Counselllor/Counsellor-Web#237]
**Describe the bug**
In the user signup page , it is possible for the user to checkmark both student and counsellor button simultaneously.

**To Reproduce**
1. Go to 'https://counsellor-startup.netlify.app/'
2. Click on 'Sign Up'
3. Click on any one of the radio buttons in "Are you a Student or a Teacher"
4. Then click on the other radio button

**Expected behavior**
Under the section "Are you a Student or Counsellor", the user should be able to select only 1 of the options either Student or Counsellor. Selecting both the buttons makes it ambiguous.

**Screenshots**
https://github.com/Counselllor/Counsellor-Web/assets/127319225/7bec325f-24e6-4b17-be28-234ab598ce8e

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser : Brave, chrome
 - Version : 2H22

Please assign me this issue, I can fix this issue . 

Thank You, 
Sayantan Choudhury
GSSOC'23 Contributor

**Comment by thestarsahil** [comment]
Its Done
