### ISSUE TITLE
Simultaneous Selection of Student and Counselor

### ISSUE THREAD

**Issue by RitiChandak** [Counselllor/Counsellor-Web#240]
**Describe the bug**

The student and counselor roles were both selected simultaneously and cannot be deselected.

**To Reproduce**

**Expected behavior**
only one should be selected at a time

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/96969496/be961e82-9640-46a1-8a6c-5effcd8ae64f)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thestarsahil** [comment]
Go ahead !
