### ISSUE TITLE
[Docs] Broken link in `Need more Help?` Section

### ISSUE THREAD

**Issue by jfmartinz** [Counselllor/Counsellor-Web#246]
I would like to fix this issue by adding an alternative resource to `learn GitHub from scratch` or if you have recommendation resource that you can provide for me, so that I can start working on this, thank you! 

You can browse the issue [here](https://github.com/Counselllor/Counsellor-Web/blob/master/CONTRIBUTING.md)

issue: 
![image](https://github.com/Counselllor/Counsellor-Web/assets/129386460/363c856b-e491-47ca-a2ed-1e9c23052451)
![image](https://github.com/Counselllor/Counsellor-Web/assets/129386460/e131851f-5a9b-43a2-9154-7d5a864008c9)

Assign this to me under GSSOC

**Comment by jfmartinz** [comment]
@thestarsahil can you check this issue?

**Comment by thestarsahil** [comment]
Yes I checked 
GO ahead !
