### ISSUE TITLE
sign up not visible

### ISSUE THREAD

**Issue by RitiChandak** [Counselllor/Counsellor-Web#266]
**Describe the bug**

sign up button is not visible and the website is not responsive

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/Counselllor/Counsellor-Web/assets/96969496/875d02ee-6967-4503-a181-2106a2af9e62)
![image](https://github.com/Counselllor/Counsellor-Web/assets/96969496/43845d9e-f7c6-4220-a62b-bc9b94da782d)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by RitiChandak** [comment]
@thestarsahil please assign me this issue

**Comment by thestarsahil** [comment]
It's already been done !
If you are looking for new bugs and issue feel to reach us !
