### ISSUE TITLE
Need to be proper responsive for galaxy fold devices...

### ISSUE THREAD

**Issue by Brijesh1963** [Counselllor/Counsellor-Web#275]
Need to be proper responsive for galaxy fold devices...

Its cut down the header part....
![responsive](https://github.com/Counselllor/Counsellor-Web/assets/98037970/cdc16a88-0292-4e62-8994-1b5c9e8eede7)

please assign me this issue....

**Comment by thestarsahil** [comment]
Thank for rasing this issue but its already done
