### ISSUE TITLE
[fix]:cors error in the signup page and no alerts when submitting data or incorrect data

### ISSUE THREAD

**Issue by lokesh-katari** [Counselllor/Counsellor-Web#28]
hey @thestarsahil the signup form does not responding and no validation and also there is an cors issue in the backend of the application can you assign it to me so,i can resolve it under gssoc'23

thanking you

**Comment by lokesh-katari** [comment]
![counsellor](https://github.com/thestarsahil/Counsellor/assets/111894942/a5c0e012-751a-4754-9cab-c04db6d5c3c7)
here is the screen shot of the issue

**Comment by KamalSritha-04** [comment]
Can i please get assigned to this issue under GSSOC'23? I have skills to solve this issue.

**Comment by lokesh-katari** [comment]
@KamalSritha-04  i am also waiting to this issue to be assigned

**Comment by thestarsahil** [comment]
Collaboration @lokesh-katari @KamalSritha-04 
Remember to provide detailed information about the issues you've identified, such as error messages, steps to reproduce the problem, and any relevant logs or code snippets. This will help the team understand and address the issues more effectively.

**Thank you for your understanding, and I wish you the best of luck in resolving the problems and contributing to the project under GSSoC'23.**

Make sure to Join Discord Server and Slack Server To communicate with other devlopers .

**Comment by lokesh-katari** [comment]
Ok and thankyou @thestarsahil

**Comment by KamalSritha-04** [comment]
ya sure, Thank you @thestarsahil
