### ISSUE TITLE
[DOCS] Adding a "Table on content" in the readme to make it easier to navigate 

### ISSUE THREAD

**Issue by 1Shubham7** [Counselllor/Counsellor-Web#293]
We must add a "Table of content" in the readme of the project to make it easier to navigate and more professional.

An example would be ->

![image](https://github.com/Bookingjini-Labs/bookingjini-icons/assets/116020663/5128f19d-30f0-4c61-accb-8656cdfbb841)

**Comment by thestarsahil** [comment]
Thank you @1Shubham7 for taking our attention  on it 
Go ahead !
Happy Coding

**Comment by 1Shubham7** [comment]
@thestarsahil Please review it, today is the last day for GSSoC
