### ISSUE TITLE
Signup button not visible

### ISSUE THREAD

**Issue by sumitkr2000** [Counselllor/Counsellor-Web#294]
**Describe the bug**

Hey, @thestarsahil  The signup buttons are not visible due to the hard-coded max height of the container. Please assign me this issue. Thank you!

**To Reproduce**

**Expected behavior**

Sign up buttons visible

**Screenshots**

![image](https://github.com/Counselllor/Counsellor-Web/assets/100675296/adb8c29b-660e-4288-a482-cf239f2a863c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thestarsahil** [comment]
its done
