### ISSUE TITLE
{GSSoC'23} Adding Login Screen

### ISSUE THREAD

**Issue by Daksh-Goel12** [Counselllor/Counsellor-Web#299]
I have made the Login Screen using Flutter and Dart. @thestarsahil 
![image](https://github.com/Counselllor/Counsellor-Web/assets/123328399/3deca372-b384-4881-b0fb-b29eae7a100e)

My pull request has been merged, please check and give me points
https://github.com/Counselllor/Counsellor-Mobile/pull/4

**Comment by thestarsahil** [comment]
Thanks for your lovely contribution at Mobile Repo as GSSOC23
