### ISSUE TITLE
Add footer in home page below login/signup section

### ISSUE THREAD

**Issue by AlfiyaSiddique** [Counselllor/Counsellor-Web#301]
**Description**
I want to add a footer on the home page where there is the login/signup form. I will add the footer below them and make it fixed and also swap the image and the form side and implement a better scroll behavior and layout.

@thestarsahil please assign me this issue under gssoc23 label.

**Comment by thestarsahil** [comment]
Go Ahead !

**Comment by AlfiyaSiddique** [comment]
@thestarsahil  just a friendly reminder that you might forgot to add gssoc23 labels on my signup/login merged pr  #290

Can you please add the labels, otherwise the contributions are not counted.

**Comment by thestarsahil** [comment]
Done ! 
Thanks For the Reminder !

**Comment by AlfiyaSiddique** [comment]
@thestarsahil For footer content I will add the copyright [dynamic year] line and add the social media icons. For social media icon links, if there are separate accounts on social media for this application then we can add that. Else I will link your social media accounts.

Is this okay, should I proceed with this??

Also can you please review issue #302, In this issue I have provided a solution to the problem of not being able to run the project in the local environment.

**Comment by thestarsahil** [comment]
Footer Include :
About page 

Blog page 
Help page
Privacy page
Terms page 
Contact us page
Open Source Contribution Page

**Comment by AlfiyaSiddique** [comment]
> Footer Include : About page Blog page Help page Privacy page Terms page Contact us page Open Source Contribution Page

@thestarsahil just to inform you that as these pages are not developed yet so the links will not redirect anywhere.

**Comment by AlfiyaSiddique** [comment]
@thestarsahil  Provide your feedback on this. 👇🏻👇🏻

https://github.com/Counselllor/Counsellor-Web/assets/86224794/091b8199-10b8-43ae-8bc7-25d8ef5c1aaa

**Comment by thestarsahil** [comment]
> 

Its Okay ...We are working on this

**Comment by thestarsahil** [comment]
> > Footer Include : About page Blog page Help page Privacy page Terms page Contact us page Open Source Contribution Page
> 
> @thestarsahil just to inform you that as these pages are not developed yet so the links will not redirect anywhere.

Its Okay We are Working On this !

**Comment by thestarsahil** [comment]
Raise PR , Its Good
