### ISSUE TITLE
In Signup page there is only one show password field in password but not in confirm password [GSsoc'23]

### ISSUE THREAD

**Issue by Monilprajapati** [Counselllor/Counsellor-Web#308]
**Describe the bug**
As you can see that there is only one eye button/password shower which handles both the password and confirm password field.
It is not a convenient way to show password both password and confirm password must have its own password shower.

I will add that functionality to confirm password field and will make it more user friendly!!

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/99136041/bcea975e-b4d7-4a64-8c20-2167703aec5e)

**Desktop (please complete the following information):**
 - OS: windows
 - Browser : chrome

Active contributor [GSsoc'23]

**Comment by thestarsahil** [comment]
Go ahead !

**Comment by thestarsahil** [comment]
Raise PR before 10Aug otherwise credit points will not be consider

**Comment by Monilprajapati** [comment]
Yeah Sure.
