### ISSUE TITLE
login with google in signup page

### ISSUE THREAD

**Issue by shraddha761** [Counselllor/Counsellor-Web#309]
**Is your feature request related to a problem? Please describe.**
I think there should login with google functionality in signUp page 

![image](https://github.com/Counselllor/Counsellor-Web/assets/106100728/a36e2802-2c38-4669-9d69-086292884c99)

Assign this issue to me under GSSOC'23

**Comment by thestarsahil** [comment]
This Feature is not using in this project !
Thank you !
