### ISSUE TITLE
Scroll to top

### ISSUE THREAD

**Issue by shraddha761** [Counselllor/Counsellor-Web#319]
**Is your feature request related to a problem? Please describe.**
There should scroll to top button to the website
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Assign this issue to me under GSSOC'23

**Comment by AshitaBidkar** [comment]
I want to work on this issue, kindly assign it to me.

**Comment by JiyaGupta-cs** [comment]
@thestarsahil
I would like to work on this under IWOC
