### ISSUE TITLE
I will redesign this footer will make it perfect for website [GSsoc'23]

### ISSUE THREAD

**Issue by Monilprajapati** [Counselllor/Counsellor-Web#327]
As you can see on the login and signUp page there is a footer section which does not look good so i will recreate it will add all the links provided by you.

Here you can see::

![image](https://github.com/Counselllor/Counsellor-Web/assets/99136041/91cd8441-d715-4762-9443-55e5a1e40755)

**Comment by AshitaBidkar** [comment]
I've developed many websites, I want to work on this issue, kindly assign it to me.
I am sharing my recent designs of footer.

![footer 1](https://github.com/Counselllor/Counsellor-Web/assets/93013385/2be3e02a-7dbc-4c26-9ccb-e1f6f1c7f49d)
![footer 2](https://github.com/Counselllor/Counsellor-Web/assets/93013385/f038d5ac-5533-4fca-9662-e4a38cc9e8ed)
