### ISSUE TITLE
Add Hover Effect on Navbar

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [Counselllor/Counsellor-Web#35]
![Screenshot 2023-05-24 225437](https://github.com/thestarsahil/Counsellor/assets/125626654/28cd1b57-60fb-4659-8bab-c351667cf8da)
Want to add hover effect
@thestarsahil, As a gssoc'2023 contributor I want to work on this feature please assign me

**Comment by sagarb2003** [comment]
Please assign me this task under GSSoc'23
