### ISSUE TITLE
Adding Tech Stacks Used In ReadMe Section 

### ISSUE THREAD

**Issue by abhi03ruchi** [Counselllor/Counsellor-Web#37]
I want to add Technology Stack used in the ReadMe. This would be quite helpful for contributors who are looking forward to contributing to the site.

This would enhance the readMe section.
Plz, assign me this task.

**Comment by Yogesh-7523** [comment]
@thestarsahil i would like to contribute to this amazing open source project in solving the issue by making a read me section more easy to understand and various tech stacks and how much they are used.
please assign this to me under gssoc 23

**Comment by thestarsahil** [comment]
@Yogesh-7523 @abhi03ruchi 
Once you have both completed your tasks, you can review each other's work and make any necessary changes. Once you are both satisfied with the results, you can merge your changes into the main codebase.

I'm looking forward to seeing what you both can create!
Happy Collaboration !

**Comment by abhi03ruchi** [comment]
Resolved Issue #37, please review and merge.
