### ISSUE TITLE
Broken Image Link On Home Page

### ISSUE THREAD

**Issue by JiyaGupta-cs** [Counselllor/Counsellor-Web#417]
**Describe the bug**
Broken Image Link On Home Page

**To Reproduce**
Go to 'Home Page'

**Screenshots**

![image](https://github.com/Counselllor/Counsellor-Web/assets/140608790/783ade90-8157-4759-94cc-fd310b56ef13)

Please assign me this issue under IWOC

**Comment by thestarsahil** [comment]
Thanks for letting know us ! We appreciate your time and efforts , but can you please look over to harder and bigger issues 
The issue you mentioned it just a simple and easy in one go solution
