### ISSUE TITLE
[IMPROVE] Signup code can use single object to form fields

### ISSUE THREAD

**Issue by aashi-ihsaa** [Counselllor/Counsellor-Web#47]
Use useState with object for form fields: Instead of having separate state variables for each form field (e.g., firstName, surname, email, etc.), you can use a single state object using useState to manage all the form fields together.

This will make code better readable and robust. Assign me this under GSSOC'23. I have already worked on it.

**Comment by thestarsahil** [comment]
@aashi-ihsaa 
That's a great suggestion! Using a single state object with useState to manage all form fields together can indeed improve code readability and make it more robust. It helps in organizing and handling form data more efficiently.

To implement this approach, you can define a state object using useState and initialize it with the initial form field values. Then, you can update the state object whenever a form field value changes by using the onChange event handlers of the form inputs.
Creating a separate branch for this task is a good practice to keep the changes isolated and organized.
