### ISSUE TITLE
feat: FAQ section

### ISSUE THREAD

**Issue by SINJINI-G** [Counselllor/Counsellor-Web#50]
## Problem 
There is no FAQ section for users to get quick answers to frequently asked questions.

## Solution
I will add a FAQ component 

**Please assign this issue to me under gssoc.** @thestarsahil

**Comment by soorjya** [comment]
I can help improve the FAQ pages by some of the frequently asked question or can take some review from some people about it so please do assign this issue to me under GSSOC'23

**Comment by thestarsahil** [comment]
@SINJINI-G and @soorjya 
As mentioned by @ShanviJha30, she will be working on implementing the FAQ component. However, we also need a UI design for the FAQ section. It would be great if either of you could work on creating a UI design for the FAQ section, keeping in mind the project's overall design language and user experience.

Once the UI design is ready, we can proceed with the implementation of the FAQ component. Please feel free to collaborate and discuss any design ideas or requirements in the discussion section.

**Comment by karantec** [comment]
Please assign me under GSSOC 2023
