### ISSUE TITLE
implementing search and filter functionality of the basis of college name and improving the UI of search bar.

### ISSUE THREAD

**Issue by piyush-gpt** [Counselllor/Counsellor-Web#507]
The search bar on dashboard page to search and filter upon colleges is not working and I want to fix it so that it gets functional.

users would be able to search and filter colleges on the basis of their name and location.

Also the UI of search bar is not attractive and so I want to make it look better.

Please assign this issue to me under GSSOC.  Thanks!.

**Comment by thestarsahil** [comment]
@piyush-gpt Thanks for Noticing a such good Bug 🐛 
I am assigning this issue to you under Gssoc24 

If you have any other queries please ask 
Thanks 👍🏻😊

**Comment by piyush-gpt** [comment]
@thestarsahil   made PR for the same

**Comment by Artuiro-23** [comment]
I can do this task. Kindly assign me this task.
Thankyou.

**Comment by thestarsahil** [comment]
@Artuiro-23 Every Issue is respected to own contributor 
Please Raise Another Issue and Add Issue that will more reliable to work on ! 
Thank you
