### ISSUE TITLE
Bug : Misspelled word 'Carrier Support' in dashboard

### ISSUE THREAD

**Issue by BHS-Harish** [Counselllor/Counsellor-Web#511]
**Describe the bug**
In the Menu bar "Career Support" was misspelled as 'Carrier Support'

**To Reproduce**
1. Go to 'https://counsellor.social/'
2. Click on 'Login'
3. Once you logged in, In the top Menu bar you can see the work carrier support

**Expected behavior**
The correct word is "Career Support"

**Comment by BHS-Harish** [comment]
Hello @thestarsahil 

Please assign this issue to me

Thanks in advance

**Comment by thestarsahil** [comment]
That's a very minor mistake not a bug , Please issue some important and find out major problems 
Thank you !
