### ISSUE TITLE
 Icons Not Linking Properly to the actual webpage on contact page

### ISSUE THREAD

**Issue by SabanaSultana** [Counselllor/Counsellor-Web#512]
**Is your feature request related to a problem? Please describe.**
 When users click on these icons, they are not being redirected to the expected destination. There are 3 icons linkedin, github and mail but they are not linked.

**Describe the solution you'd like**
Either provide the link of the pages related to icons so that I can add the link  or remove the icons so that there won't be any confusion to click the link.

![Screenshot (1449)](https://github.com/Counselllor/Counsellor-Web/assets/124595925/3bb25780-2459-46d5-a238-c6d9348dba74)

**Comment by SabanaSultana** [comment]
@thestarsahil  I would like to work on the issue, pls assign me.

**Comment by thestarsahil** [comment]
Actually @SabanaSultana right now pages and mail not created they will created at the end phase ....So right now I am closing this issue which is not relevant for now 
Thank You !
