### ISSUE TITLE
Add a page for Profile

### ISSUE THREAD

**Issue by SabanaSultana** [Counselllor/Counsellor-Web#513]
**Is your feature request related to a problem? Please describe.**
  The  'Profile' button in the navbar is static. which is lacking  the functionality to enhance user experience."

**Describe the solution you'd like**
 When clicking on 'Profile' button it should redirect to a page where user's profile will be shown.

**Comment by SabanaSultana** [comment]
@thestarsahil  I would like to work on the issue, pls assign me under gssoc24.

**Comment by thestarsahil** [comment]
Great to hear that you are working for Profile page 
Good to go

**Comment by Sid-80** [comment]
@thestarsahil I am willing to work on this issue!

**Comment by thestarsahil** [comment]
@CoderSwarup He Did it already.... @Sid-80 I request kindly look into another major problems! 
Thanks
