### ISSUE TITLE
feat: back to top button

### ISSUE THREAD

**Issue by SINJINI-G** [Counselllor/Counsellor-Web#52]
I will add a back to top button that will improve user navigation. 

Can you please assign this issue to me under gssoc? @thestarsahil

**Comment by soorjya** [comment]
I will add a back to top button that will improve user navigation.

Can you please assign this issue to me under gssoc?

**Comment by thestarsahil** [comment]
@SINJINI-G 
As we currently need a UI/UX designer to expand the design, I will assign you to this task under the GSSOC'23 tag.
Your role will involve enhancing the UI/UX of the project by expanding the design. This could include improving the visual elements, layout, typography, color scheme, and overall user experience.

Your new task is to create a split login page design for desktop mode and a single form design for mobile mode. This will ensure a responsive and user-friendly experience across different devices.

I am assigning you this task, and I'm confident that you'll be able to design and implement the login page in a way that meets the specified requirements. If you have any questions or need further clarification during the development process, please don't hesitate to reach out for assistance.

Thank you for your dedication to GSSOC'23 and your contributions to the project. Good luck with the task, and I'm looking forward to seeing your work!

**Comment by SINJINI-G** [comment]
Hi @thestarsahil !! It seems to address a lot of different issues.. so shall I make separate issues for each of the requirements for better work management??

**Comment by thestarsahil** [comment]
> Hi @thestarsahil !! It seems to address a lot of different issues.. so shall I make separate issues for each of the requirements for better work management?? 

Sure Go-ahead !

**Comment by SINJINI-G** [comment]
Ok.. first I will complete this issue.. then will make the new ones.

> > Hi @thestarsahil !! It seems to address a lot of different issues.. so shall I make separate issues for each of the requirements for better work management??
> 
> Sure Go-ahead !
