### ISSUE TITLE
Course Page

### ISSUE THREAD

**Issue by Nitin8426** [Counselllor/Counsellor-Web#523]
Hey I can Create the Responsive Frontend of the Course page with the features and relevant filter. kindly  assign me this issue under GSSoc 2024

**Comment by thestarsahil** [comment]
Yes , sure 
Just take a reference of about page !

**Comment by Sid-80** [comment]
@thestarsahil I am willing to work on this issue!

**Comment by thestarsahil** [comment]
@Ratangulati Already working...
