### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [Counselllor/Counsellor-Web#527]
**Is your feature request related to a problem? Please describe.**
In your application anyone can enter using **temporary or disposable email**.
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

**Describe the solution you'd like**
I'll implement some script that will help to detect such emails.
**Describe alternatives you've considered**

**Additional context**
Assign me this work under GSSoC24, I will implement it.

**Comment by thestarsahil** [comment]
Thanks for letting know issue #517  is also the same 
Raise PR as soon as possible !
