### ISSUE TITLE
Add social media and feedback section in blog page

### ISSUE THREAD

**Issue by rajlaxmi03** [Counselllor/Counsellor-Web#530]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
@rajlaxmi03 Please describe in details how you gonna contribute !

**Comment by thestarsahil** [comment]
Thanks @rajlaxmi03 but this area we are not working now !
If you can work on database section 
You can work on storing college data to be store in database

**Comment by rajlaxmi03** [comment]
Ok I can work on it
