### ISSUE TITLE
bug: Login Page must be single page to show call to action

### ISSUE THREAD

**Issue by mukulpythondev** [Counselllor/Counsellor-Web#536]
**Describe the bug**
The website's login page currently includes a scrollbar, which can lead to an inconsistent user experience. Additionally, the links to the Play Store and Microsoft Store are displayed below the scrollbar, potentially causing users to miss them. Consider consolidating the login page to a single page layout to streamline navigation and ensure prominent visibility of the app store links.

**To Reproduce**
1. Go to 'Login Page'
2. Scroll down to Page
3. See the links of play store and microsoft store

**Comment by thestarsahil** [comment]
Done ...Please look for another problem which is major in application and consists of level3 
Thank you !
