### ISSUE TITLE
ABOUT US PAGE

### ISSUE THREAD

**Issue by CS251000** [Counselllor/Counsellor-Web#537]
**Is your feature request related to a problem? Please describe.**
The site does not make it clear what is the aim and purpose of the project. The user has ambiguous idea about the site's features

**Describe the solution you'd like**
A responsive about us page would be useful to enhance user experience and give him/her a better understanding of the project

Kindly assign this under GSSOC

**Comment by Rv43** [comment]
can you please assign me this issue

**Comment by thestarsahil** [comment]
Sorry not working in this area !
Please raise issue to database and data related problems
