### ISSUE TITLE
Add Help/FAQ Section to website

### ISSUE THREAD

**Issue by MastanSayyad** [Counselllor/Counsellor-Web#539]
On clicking on 'Help' in the footer I would like to Add a FAQ (Frequently Asked Questions) section within it can provide a clear and concise answer to common questions related to the platform, and services offered.

Could you **please assign this task to me under GSSoC '24?**

**Comment by MastanSayyad** [comment]
Hey, @thestarsahil sorry to interrupt you but could you please assign this issue to me?

**Comment by thestarsahil** [comment]
@MastanSayyad Welcome !
Go to go and if you have any queries regarding this drop message in counsellor project channel under gssoc !
