### ISSUE TITLE
In Dashboard One image is not being shown properly

### ISSUE THREAD

**Issue by irfan-iiitr** [Counselllor/Counsellor-Web#541]
**Describe the bug**

**To Reproduce**
1. Go to 'Dashboard PAge'
4. See the Search Bar

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/123577873/2f3fc88b-e542-43bd-b8fa-e26107927903)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by irfan-iiitr** [comment]
Please assign me this.

**Comment by thestarsahil** [comment]
Sorry we are not working on this ! Please raise issue regarding the database problem
