### ISSUE TITLE
Creation of a better Issue Template

### ISSUE THREAD

**Issue by irfan-iiitr** [Counselllor/Counsellor-Web#542]
Sections for:
1. Description
2.  Steps for implementation
3.  ScreenShots
4.  A dropdown menu to ask for whether the contributer is contributing for ay program.

If a user selects any Program like gssoc24 in the dropdown menu. and the issue gets assigned to it.
Github Workflow to automaticaly add gssoc24 label on it.

**Comment by irfan-iiitr** [comment]
![Issue_template_preview2](https://github.com/Counselllor/Counsellor-Web/assets/123577873/f4a7c838-bb81-4d69-b684-906eeed31ac7)
![Issue_template_preview1](https://github.com/Counselllor/Counsellor-Web/assets/123577873/c99dc7a7-2aaf-4960-9d44-50e794dc474e)

**Comment by thestarsahil** [comment]
Sorry not working on this ! 
Thank you
