### ISSUE TITLE
Adding a hover animation to all cards of colleges .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#543]
**Is your feature request related to a problem? Please describe.**
By adding a small animation like when user hover on the card then the hovered card will pop up

**Additional context**
![Screenshot 2024-05-17 135259](https://github.com/Counselllor/Counsellor-Web/assets/118350936/1971f87a-7283-467a-8fb4-d3de07a6eac5)

**Comment by thestarsahil** [comment]
@Hrishita-Paul She is working on this area !
Thank you letting know 
You can work on other problem related to database ....frontend almost done !

**Comment by Hrishita-Paul** [comment]
@thestarsahil Sir do I need to add animation while hovering on the card as suggested in this issue or is it the same thing as already merged today?

**Comment by Ayushmaanagarwal1211** [comment]
ok

**Comment by thestarsahil** [comment]
> @thestarsahil Sir do I need to add animation while hovering on the card as suggested in this issue or is it the same thing as already merged today?

Yes Make a issue and Work on Hover effects

**Comment by Hrishita-Paul** [comment]
Sure sir
