### ISSUE TITLE
A dot icon is present in the navbar and do nothing .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#545]
**Describe the bug**

I can see a small dot in the navbar and also giving pointer when hovering like all buttons but after clicking on that it does nothing .

**To Reproduce**
1. Go to nomepage
2. Hover on (" . ") dot symbol in navbar 
3. You can see after clicking on that nothing happens .

**Expected behavior**
It must be remove or not giving pointer effect .

**Screenshots**

![Screenshot 2024-05-17 135426](https://github.com/Counselllor/Counsellor-Web/assets/118350936/02b77d91-742f-4fc7-969b-f1a9d07607ef)

**Comment by thestarsahil** [comment]
Please @Ayushmaanagarwal1211 look to major problem in application that consists of level 3
Thank you and happy coding !
