### ISSUE TITLE
Unnecessary question mark

### ISSUE THREAD

**Issue by Chinmayeep58** [Counselllor/Counsellor-Web#547]
The question mark in the phrase "Discover who we are?" is unnecessary. When inviting the user to discover our website question mark doesn't seem required.

![image](https://github.com/Counselllor/Counsellor-Web/assets/146485755/ad0232c7-ad49-4e72-b73e-116ed1e87d28)

Please assign this issue to me.
Thank you

**Comment by thestarsahil** [comment]
@Chinmayeep58 We are happy to know that you are contributing but we are accepting  big changes (level3 ) so that after same contributor can change minor changes
