### ISSUE TITLE
Add "Privacy, Terms and Join us" Pages to the website.

### ISSUE THREAD

**Issue by MastanSayyad** [Counselllor/Counsellor-Web#556]
Hey @thestarsahil as you can see following links are absent.

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/71676305-96d3-43e8-bfab-255cae542061)

I would like to develop the pages for "Privacy", "Terms" and "Join Us", ensuring the websites design theme
Could you please assign this issue to me under GSSoC'24?

**Comment by thestarsahil** [comment]
As I previously assigned , Make sure to complete and handle this all 
Thank You 
Good to go

**Comment by MastanSayyad** [comment]
Sure I will, thank you for assigning this to me. Will start working on it immediately
