### ISSUE TITLE
Invisible socials icons  bug on footer

### ISSUE THREAD

**Issue by The-Phoenics** [Counselllor/Counsellor-Web#557]
**Describe the bug**

**To Reproduce**
1. Go to 'Login or SignUp page'
3. Scroll down to 'footer'

**Expected behavior**
The socials icons must be visible on Login page.

**Screenshots**
![socials_icon_bug](https://github.com/Counselllor/Counsellor-Web/assets/96228962/9e1c2aad-7924-4a6b-816b-27f7dc20fb75)

**Desktop (please complete the following information):**
 - OS: [Linux]
 - Browser [chrome]
 - Version [124.0.6367.201]

**Comment by The-Phoenics** [comment]
Hey @thestarsahil,
I would like to work on this for GSSoC'24. Can you please assign this to me.

**Comment by thestarsahil** [comment]
@The-Phoenics Thanks for letting know ...but thisa area is very minor. We are looking and solving major problems and Majorly caused bugs in application 

You can reach to Counsellor Project Channel under Gssoc
Other contributors sorting this ! 
Looking for your major Updates! 

Thank you

**Comment by The-Phoenics** [comment]
Got it! And where can I find "Counsellor Project Channel under Gssoc" @thestarsahil ?

**Comment by thestarsahil** [comment]
@The-Phoenics Go to Gssoc24 discord -> Search  the Counsellor project in project info channel
