### ISSUE TITLE
Build a Profile Page

### ISSUE THREAD

**Issue by CoderSwarup** [Counselllor/Counsellor-Web#559]
**Is your feature request related to a problem? Please describe.**
here's no central place to view and manage users personal information, preferences, and activity history within the application. This makes it hard to update users details, see user past interactions, and customize my experience.

**Describe the solution you'd like**
I would like to have a comprehensive profile page where users can:

View and edit their personal information such as name, email, and profile picture.
Customize their preferences and settings.
View their activity history, including interactions, saved streams/branches, and chosen colleges.
Access personalized recommendations based on their profile data.

**Describe alternatives you've considered**

**Additional context**

please assign me this issue i want to work on this

**Comment by thestarsahil** [comment]
Here a hero came ! We are looking for someone willing to contribute in profile section !
Keep the ui more simple . compact and premium as reference take from readme file 
Thank , If you any doubt and query let us know at discord channel under Gssoc24

**Comment by CoderSwarup** [comment]
"Thank you, @thestarsahil. Could you provide me with some guidance on what exactly should be included in the profile section? There are several elements that the website requires, such as:

1. User data
2. History of counseling sessions
3. Upcoming counseling sessions
4. If the user is a counselor, the same information should be available for them
5. Additionally, if the user is a counselor, a different UI may be required.

**Comment by thestarsahil** [comment]
Let's discuss this on discord via VC around after 10pm ?

**Comment by CoderSwarup** [comment]
> Let's discuss this on discord via VC around after 10pm ?

sure 

discord username : coderswarup999

**Comment by CoderSwarup** [comment]
@thestarsahil  hi

**Comment by thestarsahil** [comment]
Sorry @CoderSwarup I am meeting right now 
We can catch tomorrow morning after 10am !

**Comment by CoderSwarup** [comment]
ok

**Comment by thestarsahil** [comment]
What's the update ? @CoderSwarup

**Comment by CoderSwarup** [comment]
can you send me the basic structure of the profile in a draw from 
then I will start to building according to that 

Send me the basic design , just in a draw from

**Comment by JrG-One** [comment]
@thestarsahil I also want to work on this issue.

**Comment by CoderSwarup** [comment]
@thestarsahil any update

**Comment by thestarsahil** [comment]
@CoderSwarup Are you able to meet 7:15pm on discord ?

**Comment by CoderSwarup** [comment]
sure

**Comment by thestarsahil** [comment]
thestarsahil#0568

**Comment by thestarsahil** [comment]
@CoderSwarup

**Comment by CoderSwarup** [comment]
i send  request
