### ISSUE TITLE
Auto Commenting when a PR is merged 

### ISSUE THREAD

**Issue by suhanipaliwal** [Counselllor/Counsellor-Web#560]
This feature aims to solve the problem of inconsistent and delayed communication following the merging of PRs. By automating the commenting process, it ensures that contributors receive timely feedback and acknowledgments. It also reduces the administrative burden on maintainers, allowing them to focus more on code reviews and other critical tasks.

Could you please assign me this issue under GSSOC'24.

**Comment by thestarsahil** [comment]
This season we are looking for major problem and solution containing level 3
We are more focusing into Building WebApplication rather then this side part , So request you to raise problem related to building application.
I appreciate your contribution approach !
Thanks !
