### ISSUE TITLE
[Feat]: Workflow for commenting on PR Raised

### ISSUE THREAD

**Issue by Asymtode712** [Counselllor/Counsellor-Web#563]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to a problem. When contributors raise pull requests (PRs) in a project, it is crucial to provide immediate acknowledgment and feedback to encourage collaboration and maintain transparency. However, manually commenting on every PR can be time-consuming for maintainers, leading to delays and inconsistency in communication. This can result in contributors feeling undervalued or discouraged from further participation.

**Describe the solution you'd like**
This solution introduces a new GitHub Actions workflow that automatically comments on new and updated pull requests. This feature aims to streamline the contribution process by providing contributors with immediate feedback and guidance upon creating or updating their pull requests.

![PR raised](https://github.com/Counselllor/Counsellor-Web/assets/115717746/3f212306-7a83-4371-89c5-152e5279ff77)

**Comment by Asymtode712** [comment]
@thestarsahil please assign me this issue under gssoc'24

**Comment by thestarsahil** [comment]
This season we are looking for major problem and solution containing level 3
Please look onto some other major problem
Thanks !
