### ISSUE TITLE
Year needs to be dynamic in footer

### ISSUE THREAD

**Issue by kapilG0** [Counselllor/Counsellor-Web#568]
**Is your feature request related to a problem? Please describe.**
![Screenshot_20240522_122933](https://github.com/Counselllor/Counsellor-Web/assets/59639410/f3d03a36-0f3f-4702-9b30-75fad1f8a27f)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kapilG0** [comment]
Hello @thestarsahil please assign this issue to me under gssoc 24

**Comment by thestarsahil** [comment]
This season we are looking for major problem and solution containing level 3 
Please look onto some other major problem
