### ISSUE TITLE
Enhancing the Search Bar

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#570]
**Is your feature request related to a problem? Please describe.**
The search bar does not look good. The placeholder text needs to be more lighter. The background should have been much more lighter or as the same as that of the website

**Describe the solution you'd like**
I would like to manage the background of the navbar and if permitted I would like to add hover effect on the search button

**Comment by ayush-848** [comment]
@thestarsahil If you think that the navbar does have its issue, please assign this to me. I would also like to have your inputs here.

**Comment by thestarsahil** [comment]
Welcome @ayush-848

**Comment by ayush-848** [comment]
> Shortlist major problem in one go , I am accepting those issue who are working in 5 different area ! Not accepting those who gonna work on single issue !
> 
> Your 2 problem shortlisted ! I am assigning for this now



Hey @thestarsahil didn't quite understood what you were trying to convey.

**Comment by ayush-848** [comment]
Do you mean to say that there are multiple people working on this section (i.e navbar)

**Comment by thestarsahil** [comment]
We are accepting majorly those PR ,  those contributor repeatedly contribute !
I mean not like only single contribution towards the project !

**Comment by ayush-848** [comment]
Oh ok

**Comment by ayush-848** [comment]
@thestarsahil 
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/8c666aba-1cb4-41f7-aab2-245c3d1a1ba2)
is there no image here?

**Comment by ayush-848** [comment]
@thestarsahil 
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/1efb6aec-3500-41aa-9df3-ff932255ea62)
how does it look?? should I do a PR?

**Comment by thestarsahil** [comment]
There is not much gap between the img and the border in the searchbar

**Comment by ayush-848** [comment]
> There is not much gap between the img and the border in the searchbar

![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/323cf1c6-2e58-4fa4-9204-e6e33a13d916)

are you talking about this part??

**Comment by thestarsahil** [comment]
@ayush-848 Yes

**Comment by ayush-848** [comment]
@thestarsahil now see
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/b3db23c9-2421-4480-9e31-b288f6a32d6e)

**Comment by thestarsahil** [comment]
Inside the Search bar div element , that should be round from the corner as you can see the outer round its mild curve !

**Comment by ayush-848** [comment]
> Inside the Search bar div element , that should be round from the corner as you can see the outer round its mild curve !

The search image???

**Comment by thestarsahil** [comment]
> > Inside the Search bar div element , that should be round from the corner as you can see the outer round its mild curve !
> 
> The search image???

No , as you can see the element written => Type college name or university name 
from the side corner it should be little curve not rectangle corner

**Comment by ayush-848** [comment]
oh understood

**Comment by ayush-848** [comment]
@thestarsahil 
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/efc499a7-4cbf-4184-a9ee-6b46f266022a)
please check

**Comment by thestarsahil** [comment]
Update the PR
