### ISSUE TITLE
[Enhance]The Navbar

### ISSUE THREAD

**Issue by sau-mili** [Counselllor/Counsellor-Web#571]
I would like to enhance the Navbar UI with animations and suitable changes that will align with the theme

**Comment by thestarsahil** [comment]
@sau-mili Good to go but make sure We are accepting majorly those PR those contributor repeatedly contribute !
I mean not like only single contribution towards the project !
Thanks you !

**Comment by sau-mili** [comment]
Don’t worry.. I am pretty consistent except for days when I have Class Tests

**Comment by sau-mili** [comment]
https://github.com/Counselllor/Counsellor-Web/assets/146661411/b63ee9ab-faa5-4078-b9da-559e1b398ee4

Please check if this is okay
