### ISSUE TITLE
[BUG] [UI] Searchbar UI 

### ISSUE THREAD

**Issue by Ratangulati** [Counselllor/Counsellor-Web#574]
**Describe the bug**
There is not much gap between the img and the border in the searchbar and it is not according to the img in the readme.

**Before
<img width="1090" alt="Screenshot 2024-05-23 at 7 52 29 PM" src="https://github.com/Counselllor/Counsellor-Web/assets/116749593/500e946e-3cda-4ab0-8fbe-35176d19dfae">

**Expected behavior**
I have tried doing it and this is the result

<img width="1113" alt="Screenshot 2024-05-24 at 5 46 40 AM" src="https://github.com/Counselllor/Counsellor-Web/assets/116749593/9c8c3aae-ddc4-4c26-9f8a-9f0df0f408e6">

If you have any suggestions, I would like to work on it.

**Comment by Ratangulati** [comment]
@thestarsahil I would love to get your take on this.

**Comment by thestarsahil** [comment]
@Ratangulati Sorry for that its already been worked done !
Shall proceed to new one !
