### ISSUE TITLE
Liking socials in contact us page

### ISSUE THREAD

**Issue by AMISH-KHAN** [Counselllor/Counsellor-Web#578]
**Is your feature request related to a problem? Please describe.**

Currently in contact us page there are social icons are given like github linkedin but it does not redirect to anywhere.

![image](https://github.com/Counselllor/Counsellor-Web/assets/123164129/fe88e3fe-bc15-4f8f-b97e-01bd11874a18)

**Additional context**

please aasign this issue to me under GssoC

**Comment by thestarsahil** [comment]
Minor Problem ...I request to look into major problem consisting of level 3
