### ISSUE TITLE
Enhace the cards in About Us

### ISSUE THREAD

**Issue by Hemashree21** [Counselllor/Counsellor-Web#587]
![image](https://github.com/Counselllor/Counsellor-Web/assets/138188163/7e18c99e-cc75-416b-86f9-03ce7a75a127)

The above block looks very simple. I can enhance this and add some pictures and animation effects highlighting each block. Here is one of the template.

![Screenshot 2024-05-20 163822](https://github.com/Counselllor/Counsellor-Web/assets/138188163/fbbdade5-14fe-470b-ae15-0df90ff15817)

I can enhance it to something similar to the above template. @thestarsahil can you please assign this to me?

**Comment by thestarsahil** [comment]
Good to go !

**Comment by meenakshiiyer2531** [comment]
Hello @thestarsahil 
Can this issue be assigned to me for gssoc '24
Regards,
V Meenakshi Iyer

**Comment by thestarsahil** [comment]
@meenakshiiyer2531 Its already been merged !
If you want to contribute raise a Issue and get assigned label to work under GSSOC24
Thanks
