### ISSUE TITLE
Login and Signup Page

### ISSUE THREAD

**Issue by Sar-thak-3** [Counselllor/Counsellor-Web#59]
**Describe the bug**
The login and Signup page is not submitting. Also selecting a student/counselor is not working on the Signup page

**Expected behavior**
I will correct these issues.

**Screenshots**
![image](https://github.com/thestarsahil/Counsellor/assets/100359818/2107e6c8-d287-44ff-a64c-aae7c85b91f7)

**Comment by thestarsahil** [comment]
Thank you for reporting the issues with the login and signup page.
Goahead !
To ensure the project runs smoothly, please follow all guidelines provided.
Please do follow the [Contribution Guidelines ](https://github.com/thestarsahil/Counsellor/blob/master/CONTRIBUTING.md)
