### ISSUE TITLE
The message text-are in the contact section is not fixed 

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#600]
**Describe the bug**
The text-area can be made smaller or larger by hold & drag

**Expected behavior**
It should remain fixed

![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/f4337de4-9c92-4ae6-aaf0-36614285e473)

![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/d6fe2332-0d26-42ac-84f7-f009f6385e8e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Brave

**Comment by thestarsahil** [comment]
Good to Go !

**Comment by ayush-848** [comment]
@thestarsahil I fixed the text-area, but I found that the focus animation was working on Name and Email but not for the text area

SO I fixed that.
It's my humble request to tag this as a "level3" issue
