### ISSUE TITLE
Search icon not getting loaded

### ISSUE THREAD

**Issue by masterboy376** [Counselllor/Counsellor-Web#602]
**Describe the bug**
Search icon not getting loaded in the search bar.

**To Reproduce**
1. Go to 'https://counsellor.social/dashboard'
2. Observe

**Expected behavior**
Search icon should show up in the search bar.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Microsoft edge
 - Version: 11

**Possible soultion**
Use `/assets/icons8-search-50.png` instead of `src/assets/icons8-search-50.png`

**Comment by masterboy376** [comment]
hello @thestarsahil  I would like to work on this issue under gssoc'24. I have already setup the repo on my local machine.

**Comment by thestarsahil** [comment]
I appreciate your contribution ...but please look into major problem alteast 5 because this season we are accepting major problem and accepting minor solution those contributor who already contributed majorly !
Thanks
