### ISSUE TITLE
Enhancement of college page

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#605]
**Is your feature request related to a problem? Please describe.**
I will do enhancement of college page like by adding the some custom animations for the loading of the college and the dropdown and also giving proper margin and padding across the college image and the dropdown menu to looks good .

![Screenshot 2024-05-25 192808](https://github.com/Counselllor/Counsellor-Web/assets/118350936/25f2d644-3199-447b-8371-35e3a658f108)

**Comment by thestarsahil** [comment]
Good to go ! Make sure contribute atleast 5 major problem in building this webapp then PR will gonna merged !
Thanks

**Comment by Ayushmaanagarwal1211** [comment]
Sure
