### ISSUE TITLE
The Magnifying image in the search bar is not visible .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#609]
**Describe the bug**
In the search bar the search icon image is not showing  .
**To Reproduce**
1. Go to home page
2. See the left side of the text "Search" .
3. See error

**Expected behavior**
The image of the search is to be shown .
**Screenshots**
![Screenshot 2024-05-26 003238](https://github.com/Counselllor/Counsellor-Web/assets/118350936/f46a008b-4fc4-4a2e-b14d-d4afb2e6c390)

**Additional context**

**Comment by thestarsahil** [comment]
It is already done !
