### ISSUE TITLE
Center the card in responsive properly .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#610]
**Is your feature request related to a problem? Please describe.**

All the cards in the responsive mode is not centered properly  .

**Describe the solution you'd like**
I can do the cards center for all screen sizes .

![Screenshot 2024-05-26 003452](https://github.com/Counselllor/Counsellor-Web/assets/118350936/4fe5da5a-bad5-4d12-97b5-a59917e2b956)

**Comment by thestarsahil** [comment]
Good to go !

**Comment by Ayushmaanagarwal1211** [comment]
Ok i will start working on that .
