### ISSUE TITLE
Adding a smooth scroll animation to the top Arrow .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#611]
**Is your feature request related to a problem? Please describe.**
By adding an smooth scroll when user click on the top arrow to more to the top of the page it feels attractive. 

https://github.com/Counselllor/Counsellor-Web/assets/118350936/abca3052-08a8-46d7-aced-d9bb57212a92

**Comment by thestarsahil** [comment]
Good to Go !
