### ISSUE TITLE
Making a FAQs section

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#616]
**Is your feature request related to a problem? Please describe.**
There will be a FAQs section where few questions will  be displayed. On clicking them, the answer will be shown.

**Additional context**
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/6a96fe2d-b1c2-4530-a95f-52c774b0c772)

Like this

**Comment by thestarsahil** [comment]
Good to go !
