### ISSUE TITLE
Naming the 'Help' to 'FAQs'

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#617]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/92a434e3-460e-43b5-9aa2-e94e17fe9fec)

for issue #616

**Comment by thestarsahil** [comment]
Good to go !

**Comment by ayush-848** [comment]
@thestarsahil I was think to make the footer 'FAQ' active as a link along with changing its name

**Comment by ayush-848** [comment]
@thestarsahil I have completed it and
**please add the labels to PR #620**
