### ISSUE TITLE
The 'join us' should be in the upper row in the about section

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#618]
**Describe the bug**
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/57e89069-a354-47d6-a073-d70e8ff955c9)

it should be like this:- 
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/bccccba6-4860-4642-b771-79b806ce6b1d)

**Comment by thestarsahil** [comment]
@ayush-848 It is correct ! As we want to join us button should be in below row !

**Comment by ayush-848** [comment]
@thestarsahil ok let me make it symmetrical to the copyright text
