### ISSUE TITLE
Adding Animation

### ISSUE THREAD

**Issue by harshmishra19** [Counselllor/Counsellor-Web#619]
**Is your feature request related to a problem? Please describe.**

Your website already looks amazing but incorporating animation on all the images used on all the pages can make it even more appealing 

**Describe the solution you'd like**

I want to add floating animations on all the pages

**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
Right Now , We are not looking for this area !
You can work on another major problem 
Thanks you !
