### ISSUE TITLE
Improving the UI of Sign Up Page

### ISSUE THREAD

**Issue by Yashshukla11** [Counselllor/Counsellor-Web#62]
<h1><b>Issue :</b></h1>

I want to make the login/signup page more interactive by adding Double slider Sign in/up feature.

![signup](https://github.com/thestarsahil/Counsellor/assets/112846526/806b9496-8a95-4f9a-8c34-c467aec6ecff)
![login](https://github.com/thestarsahil/Counsellor/assets/112846526/43914969-a90f-4927-b1ad-91a7b21ac211)

I will be doing this using HTML, CSS, JAVASCRIPT.

I want to contribute to this project. 
Please assign me this project under GSSOC'23

**Comment by thestarsahil** [comment]
@Yashshukla11 
That sounds like a great idea! To contribute to the project and work on implementing the double slider sign in/up feature using HTML, CSS, and JavaScript, you should follow the project's guidelines and processes for contributing. Typically, you would fork the project repository, make your changes in a new branch, and then submit a pull request to the original repository.

Good luck with your contribution to the project, and I hope you have a rewarding experience with GSSOC'23!

**Comment by thestarsahil** [comment]
@Yashshukla11 

We would like to express our gratitude for your contributions and hard work towards the project. Your dedication and efforts have been greatly appreciated.

However, we wanted to inform you that we have recently undergone a complete redesign of the website's structure. As a result, we kindly request you to review the updated README file to ensure that your contributions align with the new structure and guidelines.
If you have any questions or need further clarification, please don't hesitate to reach out to us. We are here to support you throughout the process and assist with any challenges you may encounter.

Once again, thank you for your commitment and valuable contributions. We look forward to your continued involvement in the project.

Make Sure to join Discord Server For latest updates

**Comment by Yashshukla11** [comment]
Sure Sir I'll look into it

**Comment by Yashshukla11** [comment]
Sir, I was busy with my exam, now the login/signup page has been changed so should I continue to solve the issue.

**Comment by thestarsahil** [comment]
create a new issue !
