### ISSUE TITLE
accepting any links for any profiles

### ISSUE THREAD

**Issue by DEV-Soumya-Ranjan-Swain** [Counselllor/Counsellor-Web#631]
**Describe the bug**
it's accepting any links for any profiles

**To Reproduce**
1. Go to 'profile section'
2. Scroll down to 'social profile'
3. Click on 'add a new profile'

**Expected behavior**
if i am adding a github then it should accept only https://github.com/ 
if i am adding linkedin it should only accept https://linkedin.com/

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/136828553/5bcfdfa1-69f1-4906-a61f-3a74dc9a08ed)

Desktop (please complete the following information):
OS: Windows 11
Browser Edge
Version 125.0.2535.67 (Official build) (64-bit)

**Comment by thestarsahil** [comment]
Sorry to Say , But this Profile area  @CoderSwarup Is working 
You can choice another area !
Thanks
