### ISSUE TITLE
dummy data in profile page

### ISSUE THREAD

**Issue by DEV-Soumya-Ranjan-Swain** [Counselllor/Counsellor-Web#632]
**Describe the bug**
Everything in the profile page is dummy data

**To Reproduce**
1. go to the profile page

**Expected behavior**
these data has to be filled up by users and we have to show that

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/136828553/0cdb2314-2935-43b2-885b-e9f9240a0331)

**Desktop (please complete the following information):**
OS: Windows 11
Browser Edge
Version 125.0.2535.67 (Official build) (64-bit)

**Comment by thestarsahil** [comment]
Already @CoderSwarup working
