### ISSUE TITLE
no functionality of settings and dashboard page

### ISSUE THREAD

**Issue by DEV-Soumya-Ranjan-Swain** [Counselllor/Counsellor-Web#633]
**Describe the bug**
the settings and the dashboard have no functionality at all

**To Reproduce**
1. Go to 'profile page'
2. Click on 'settings or dashboard'

**Expected behavior**
in the settings page it should allow to update certain things and in the dashboard it should display things

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/136828553/66b43635-626a-43f0-be45-4e2cc809ee00)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Edge
 - Version 125.0.2535.67 (Official build) (64-bit)

**Comment by thestarsahil** [comment]
Already @CoderSwarup working 
Thanks
