### ISSUE TITLE
Resolving some bugs when user tries to signup/login.

### ISSUE THREAD

**Issue by yashi-15** [Counselllor/Counsellor-Web#636]
**Describe the bug**
When users are signing up or logging in on the website, proper error handling and alert displays are not implemented.

**Expected behavior**
- When I tried logging with a new email id which is not registered. The error is not handled properly, an alert should be prompting saying that the email is not registered.
> ![Screenshot (509)](https://github.com/Counselllor/Counsellor-Web/assets/132138302/0a988839-e7b9-466f-9af2-073420fb2c9f)

- After a successful log-in, an alert displaying the message "You are logged in" should appear. This alert needs to be designed to be visually appealing and in harmony with the website's overall theme. Currently, there is no alert, and the homepage opens abruptly.

- When logging out successfully, there is no alert. However, the user should receive an alert even in this situation.

- When a user inputs an incorrect password or captcha, the default browser alert is displayed. I would like to modify this alert to be more appealing and match the website's theme.

**Additional context**
Kindly assign this issue to me under GSSOC'24.

**Comment by thestarsahil** [comment]
Drop your Discord Id !
I add you in channel , then let's have more deep conversation about this issues raised by you !
Thanks

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
Hey i have already raised this issue before see #629

**Comment by yashi-15** [comment]
> Hey i have already raised this issue before see #629

Hello @DEV-Soumya-Ranjan-Swain,
I have reviewed the issue you raised regarding the warnings that appear in the console during the signup process. 
My concern, however, pertains to implementing appropriate error handling. For instance, when attempting to log in with an "unregistered" email, an error message should be displayed on the UI indicating that the email address is not registered. Additionally, there should be messages on the UI for when a user logs in or out.

**Comment by thestarsahil** [comment]
@DEV-Soumya-Ranjan-Swain Their was a confusion occur , sorry for that 1
This contributor doing this work !
Kindly look into another problem !

@DEV-Soumya-Ranjan-Swain I request you to raise more major issues

**Comment by yashi-15** [comment]
Hi @thestarsahil,
Actually, I am already done with the implementation of the issue. Should I submit the PR now? 
Additionally, I believe my issue and @DEV-Soumya-Ranjan-Swain 's issue are somewhat different. If he is also working on implementing "alerts" in the UI, there's no issue; you can merge his PR since he raised the issue before me. However, could you review my PR if he is not specifically working on the "alerts"? In that case, you might consider merging mine.

**Comment by DEV-Soumya-Ranjan-Swain** [comment]
> Hi @thestarsahil, Actually, I am already done with the implementation of the issue. Should I submit the PR now? Additionally, I believe my issue and @DEV-Soumya-Ranjan-Swain 's issue are somewhat different. If he is also working on implementing "alerts" in the UI, there's no issue; you can merge his PR since he raised the issue before me, and I am happy to contribute to more issues. However, could you review my PR if he is not specifically working on the "alerts"? In that case, you might consider merging mine.

Are you trying to implement toaster for something?

**Comment by yashi-15** [comment]
> > Hi @thestarsahil, Actually, I am already done with the implementation of the issue. Should I submit the PR now? Additionally, I believe my issue and @DEV-Soumya-Ranjan-Swain 's issue are somewhat different. If he is also working on implementing "alerts" in the UI, there's no issue; you can merge his PR since he raised the issue before me, and I am happy to contribute to more issues. However, could you review my PR if he is not specifically working on the "alerts"? In that case, you might consider merging mine.
> 
> Are you trying to implement toaster for something?

Yes! I have implemented toaster for a when user sign-in /sign-out and when captcha/password is wrong or the email is not registered. Here are some screenshots:

![Screenshot (514)](https://github.com/Counselllor/Counsellor-Web/assets/132138302/a63dba49-452f-4972-a897-98b3d616b4e4)

![Screenshot (517)](https://github.com/Counselllor/Counsellor-Web/assets/132138302/7b44207a-c921-420b-93c4-f12bb3310ed1)

@DEV-Soumya-Ranjan-Swain please let us know if you are working on the same...

@thestarsahil  Should I raise the PR?
