### ISSUE TITLE
[FEATURE] : Design Privacy Page

### ISSUE THREAD

**Issue by dhruv8433** [Counselllor/Counsellor-Web#641]
**Is your feature request related to a problem? Please describe.**
@Counselllor

there are dummy footer link,
it doesn't redirect us to any page

![image](https://github.com/Counselllor/Counsellor-Web/assets/114583978/a3894f64-cbc5-4bfd-98c7-96ac9c8c237e)

**Describe the solution you'd like**

when user click privacy link from footer we can redirect them to `/privacy`

**Comment by thestarsahil** [comment]
Would you like to work for all pages which is in footer !
This all containing level 3

**Comment by dhruv8433** [comment]
@thestarsahil 

yes, i would like to work on all of these footer pages 
can you please asssign it to me i will do all those pages

**Comment by thestarsahil** [comment]
@dhruv8433 Good to Go !

**Comment by dhruv8433** [comment]
@thestarsahil 

this is my discord user id
1103340371834056806

username 
dhruv7143

**Comment by dhruv8433** [comment]
@thestarsahil  

thank you so much
