### ISSUE TITLE
[Feature] : Add Help page

### ISSUE THREAD

**Issue by dhruv8433** [Counselllor/Counsellor-Web#644]
**Is your feature request related to a problem? Please describe.**
@Counselllor

we can add help page
when user click on `help` link from footer they will redirect to `/help` route

![image](https://github.com/Counselllor/Counsellor-Web/assets/114583978/a3894f64-cbc5-4bfd-98c7-96ac9c8c237e)

and it will look like
![image](https://github.com/Counselllor/Counsellor-Web/assets/114583978/7edb67b3-2159-4b4e-8f0c-571bd616f26a)

please assign it to me, i would like to work on this issue.

**Comment by Shineri** [comment]
@thestarsahil I would like to work on this issue.
Will you please assign it to me
