### ISSUE TITLE
[Feature] : Design Join Us Page

### ISSUE THREAD

**Issue by dhruv8433** [Counselllor/Counsellor-Web#645]
**Is your feature request related to a problem? Please describe.**

@Counselllor

when user click on `join us` link from footer, we will redirect them to `/join-us` route
and it will look like 

![image](https://github.com/Counselllor/Counsellor-Web/assets/114583978/92e337c6-dd9b-4d9c-a314-b647105b5446)

please assign it to me, i would like to work on that issue

**Comment by Monalisha-Roy** [comment]
please assign this issue to me. I would very much be pleased to work on this issue.
