### ISSUE TITLE
The search image is not visible in the search 

### ISSUE THREAD

**Issue by Sibam-Paul** [Counselllor/Counsellor-Web#648]
**Describe the bug**
The search image is not showing

**The problem**
![image](https://github.com/Counselllor/Counsellor-Web/assets/158052549/fb3cebf4-4ebc-4b15-b567-1ee319f3d819)

**Want to add the search icon to it**

_Please assign me this issue under GSSOC'24 I wanna work on it_

**Comment by Sibam-Paul** [comment]
@thestarsahil Please assign me this issue

**Comment by thestarsahil** [comment]
Minor changes not accepted , i request to focus on major problem atleast 5
