### ISSUE TITLE
Improving about page

### ISSUE THREAD

**Issue by Srija-Burugula** [Counselllor/Counsellor-Web#66]
The About page of the current version has very little information. Adding little more information to the About page along with improvement in UI will make the website more appealing. I would like to work on this issue under GSSoC'23. Please assign this issue to me.

**Comment by soorjya** [comment]
The About page of the current version has very little information. Adding little more information to the About page along with improvement in UI will make the website more appealing. I would like to work on this issue under GSSoC'23. Please assign this issue to me.

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.

**Comment by Shrivastavpratham** [comment]
i can work on this. assign me this issue under GGSoC'23
