### ISSUE TITLE
Toast Messages Not Displaying Properly For Mobile Screen

### ISSUE THREAD

**Issue by Uday2902** [Counselllor/Counsellor-Web#661]
The toast messages (e.g., Logged in! , Logged out! , Authenticating your credentials) are not displaying properly on mobile screens. The messages need to be aligned correctly to enhance user experience on mobile devices.

1. Go to [webpage](https://counsellor.social/)
2. Resize window to mobile screen
3. Do login or logout

**Expected behavior**
The toast message should be well-aligned, and consistent with the overall design of the website on mobile screens.

Below are the screenshots related to the issue : 

![Screenshot 2024-05-31 202851](https://github.com/Counselllor/Counsellor-Web/assets/127274394/fba97a64-d978-462c-8779-bda528ee4337)

![image](https://github.com/Counselllor/Counsellor-Web/assets/127274394/5a6e43d0-8aeb-4be9-a7f6-c4524cdcbe08)

![image](https://github.com/Counselllor/Counsellor-Web/assets/127274394/90df340e-3aad-4100-bd78-1d0e02a9bee1)

 - OS : Windows
 - Browser : chrome
 - Version : 125.0.6422.142

I would like to work on this issue. I request you to assign this issue to me under GSSOC'24.

**Comment by thestarsahil** [comment]
@yashi-15 She is working on it already !
Drop your discord id to get latest update from discord channel !
