### ISSUE TITLE
Correcting the Bug issues

### ISSUE THREAD

**Issue by Hrishita-Paul** [Counselllor/Counsellor-Web#664]
**Describe the bug**
Fixing the bug issues in the code like removing unused variables, removing console logs, avoiding use of index as key prop

**Comment by thestarsahil** [comment]
@Hrishita-Paul Describe the Bug and How you gonna fix that !

**Comment by thestarsahil** [comment]
@Hrishita-Paul Can you please describe the bugs ?

**Comment by Hrishita-Paul** [comment]
> Fixing the bug issues in the code like removing unused variables, removing console logs, avoiding use of index as key prop
