### ISSUE TITLE
BUG: Search icon not visible and website logo missing from footer

### ISSUE THREAD

**Issue by Ayesha-Siddiqua88** [Counselllor/Counsellor-Web#667]
**Describe the bug**
The search icon is not visible on the website, and the website logo is missing from the footer. This impacts user experience and the footer looks incomplete without the branding.

**To Reproduce**
• Go to the homepage of the website.
• Look for the search icon in the header or navigation bar.
• Scroll down to the bottom of the page.
• Observe the footer for the presence of the website logo.

**Expected behavior**
The search icon should be clearly visible and easily accessible in the header or navigation bar. The website logo should be prominently displayed in the footer to maintain brand consistency and enhance the visual appeal of the page.

**Screenshots**
![gssoc9](https://github.com/Counselllor/Counsellor-Web/assets/128472306/0ebe5d94-ef6d-446c-ab4a-68047394fa4e)

Please assign this to me under gssoc

**Comment by thestarsahil** [comment]
It is not reflecting due to proper deployment ...Its already been worked on 
kindly Request to work on major problem and Drop your Discord id to get update through discord channel
