### ISSUE TITLE
Creating An Intro to the Website

### ISSUE THREAD

**Issue by irfan-iiitr** [Counselllor/Counsellor-Web#673]
When a new User logins ..he can be given a tour of the website...highlighting the various features we offer and how to sue them.

**Additional context**

![image](https://github.com/Counselllor/Counsellor-Web/assets/123577873/235798b7-dec3-4175-ad63-f093bb3dbca8)

This is how it will Look.

I would like to work on this under the gssoc label.

**Comment by masterboy376** [comment]
Hello @thestarsahil, I would like to work on this issue under GSSOC'24.

**Comment by thestarsahil** [comment]
That's Good , but need not to work on this ! You can look into another problem 
Thanks
