### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by AkhilaSunesh** [Counselllor/Counsellor-Web#674]
**Describe the bug**
Location: Signup page
![image](https://github.com/Counselllor/Counsellor-Web/assets/140897461/a26b4559-8d71-4ebc-af03-4fd26177414c)
Its supposed to be Auto-generated 

**To Reproduce**
edit the text

**Expected behavior**
More professional

**Additional context**
Kindly assign me this issue

**Comment by thestarsahil** [comment]
Minor Changes not gonna accept , Look into major problem as you can see previous PR and Issue !
