### ISSUE TITLE
Change copyright year 2023 to 2024

### ISSUE THREAD

**Issue by ANI2707** [Counselllor/Counsellor-Web#675]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/108017771/cecc267b-005e-466d-93f5-b6a879e90b72)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ANI2707** [comment]
@thestarsahil please assign this issue to me under GSSOC’24

**Comment by thestarsahil** [comment]
That's a minor change , I request you to focus on major problem as you can take references of merged PR !
Thanks
