### ISSUE TITLE
searchicon on the search bar

### ISSUE THREAD

**Issue by tusharshah21** [Counselllor/Counsellor-Web#679]
**Describe the bug**
the search icon on the home page is not visible either the link is broken or the icon is at different location

**To Reproduce**
Would just add an svg from any platform to the place

**Expected behavior**
A new search icon embedded insted of photo 

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/96661387/903163f0-a707-47f2-8e87-f1a11ac5bcda)

**Comment by thestarsahil** [comment]
Its a minor changes, we are not looking into minor change 
I reuquest to focus on mjaor problem containing level 3 , as you can take reference from mergerd PR
