### ISSUE TITLE
Add more content in HomePage

### ISSUE THREAD

**Issue by deepeshgupta3257** [Counselllor/Counsellor-Web#68]
**Is your feature request related to a problem? Please describe.**
Yes

**Describe the solution you'd like**
Adding more content to the homepage attract the student or the viewer to get in touch with the counsellor

**Describe alternatives you've considered**
Adding similar content related to the counsellor's

Please assign me this issue under GSSOC'23. So, that I can start working on it.

**Comment by soorjya** [comment]
I can help you add more content in your home page related to counselor's so assign me this issue under GSSOC'23 so that i can 
start working on it

**Comment by khadesamrudhi** [comment]
please assign me this issue under GSSoC'23.
