### ISSUE TITLE
Redesign Footer on Homepage

### ISSUE THREAD

**Issue by AsmitaMishra24** [Counselllor/Counsellor-Web#680]
**Is your feature request related to a problem? Please describe.**
The absence of a footer on our website's homepage is causing frustration among users who struggle to find essential links and information. This omission impacts the overall user experience by making it difficult to access contact information, social media links, and critical pages such as the Privacy Policy and Terms of Service. Improving this aspect is crucial for enhancing user engagement and satisfaction.

**Describe the solution you'd like**
I propose adding a footer to the homepage that includes the following sections:

- Contact Information: Address, phone number, and email.
- Social Media Links: Icons linked to our social media pages (Facebook, Twitter, LinkedIn, etc.).
- Quick Links: Text links to key pages, including About Us, Privacy Policy, and Terms of Service.
- Newsletter Signup: A simple form to collect email addresses for our newsletter.
- Copyright Information: Text stating the website's copyright information.

The footer should be designed to align with our brand's aesthetic, ensuring it is both responsive and accessible. This addition will significantly enhance the user experience by providing easy access to important information and navigational links.

**Describe alternatives you've considered**
Alternatives such as placing this information in a sidebar or header were considered, but these options could clutter the page and detract from the main content. Another alternative was to create a separate "Contact Us" page, but embedding this information in the footer ensures it is consistently accessible without additional navigation steps.

**Additional context**
![Untitled (4)](https://github.com/Counselllor/Counsellor-Web/assets/146121869/6af671e2-2c07-4f58-9b71-a9c898e8066d)

**Comment by AsmitaMishra24** [comment]
I would like to work on this issue. Please assign me this task for GSSoC'24. @thestarsahil

**Comment by thestarsahil** [comment]
Okay , We are majoly acepting PR of repeatedly contributing contributors in this organization !
 We are welcoming you , for your first contribution towards this and look more engaging contribution towards it
