### ISSUE TITLE
add title in the navbar

### ISSUE THREAD

**Issue by jayanththalla** [Counselllor/Counsellor-Web#681]
Adding title in the navbar beside of the logo 
please assign me @pa under gssoc

**Comment by krishna25092005** [comment]
I would like to work on this project . Please assign it to me.

**Comment by thestarsahil** [comment]
Elaborate this more in details

**Comment by jayanththalla** [comment]
> Elaborate this more in details

![image](https://github.com/Counselllor/Counsellor-Web/assets/121346142/f4af1ea1-2d74-45ac-923f-a1fbf417e6da)
here to update

**Comment by thestarsahil** [comment]
Sorry to say , but we are implementing this in our webapplication 
You can check previous major issues and work on it , as this year we are focusing on level3 and major prolem
