### ISSUE TITLE
Floating animation in the log in image

### ISSUE THREAD

**Issue by Damini2004** [Counselllor/Counsellor-Web#683]
**Is your feature request related to a problem? Please describe.**
Implement floating animation to create a smooth, visually appealing movement for the input fields, captcha box, and login button. The elements should gently float or move slightly up and down, creating a dynamic and engaging user experience.

**Describe the solution you'd like**
The floating animation effect aims to improve the user interface (UI) by adding a subtle, engaging visual element to the login page. This will enhance the overall user experience (UX) by making the login process more enjoyable and visually appealing.

**Describe alternatives you've considered**
Community Engagement:

Enhanced Experience: Provides a pleasant and modern user experience, encouraging more frequent use.
Professional Appearance: Contributes to a more polished and professional appearance of the application.
Project Growth:

Attracting Users: A visually appealing login page can attract more users and increase sign-ups.
User Retention: Improves user satisfaction, potentially leading to higher retention rates.

**Additional context**
![image](https://github.com/Counselllor/Counsellor-Web/assets/119414762/68831e51-fde7-466b-a3cb-83e5871e1f4c)

**Comment by thestarsahil** [comment]
Okay , Good to go 
Raise more issues consisting of level3 because we are accepting PR of Repeatedly Contributing to this Org and make to 
Drop your Disord ID here , Connect with other peers contributors in a group !

**Comment by Damini2004** [comment]
Discord Id : _.divcxl._
