### ISSUE TITLE
X(Twitter) icon in profile section is not updated

### ISSUE THREAD

**Issue by am-1145** [Counselllor/Counsellor-Web#686]
**Describe the bug**
The X(Twitter) symbol in profile section social handle is still the old one
![image](https://github.com/Counselllor/Counsellor-Web/assets/96623227/4a0f491a-8e79-4c88-a88f-fe1c663a21ff)

Could you please assign me this issue under GSSOC. I can fix this.

**Comment by thestarsahil** [comment]
This is the minor problem , I request to focus on major problem with containing level3 as you can take reference from merged PR !
