### ISSUE TITLE
[UPDATE] Enhancing the UI of Login page

### ISSUE THREAD

**Issue by Mahitej28** [Counselllor/Counsellor-Web#70]
Hello, I am Mahima Churi, a proud contributor of GSSoc ' 23.

I would like to work on this project, by enhancing the UI of the Login page.

Things I would be working on:
📌Linking Login and Sign Up page so that the User can be directly directed to the login page
📌Enhancing the UI of the Login Page
📌Making the Login with social icons clickable

If you think it is legit then do assign me the issue under GSSoC '23 with the level of the PR as well

**Comment by thestarsahil** [comment]
Hi Mahima Churi,

Thank you for expressing your interest in contributing to the project and outlining the specific enhancements you would like to work on for the Login page. Your proposed tasks, including linking the Login and Sign Up pages, enhancing the UI, and making the social icons clickable, sound like valuable improvements that can enhance the user experience.

Considering your enthusiasm and commitment, I would be happy to assign you the issue under GSSoC '23. I appreciate your dedication to the project and your willingness to contribute.

I will assign you the issue with an appropriate level of PR, and you can proceed with the implementation of the enhancements. If you have any questions or need any further information, please feel free to ask. Good luck with your contribution, and thank you for being a part of GSSoC '23!

Best regards,
@thestarsahil

**Comment by Mahitej28** [comment]
Thankyou so much, also as currently my exams are going on I would be working from the first week of June is that okay??

**Comment by thestarsahil** [comment]
You're welcome! I understand that you have exams going on, and it's perfectly fine to start working from the first week of June. Your availability and commitment to the project are important, so take the time you need to focus on your exams and perform well. Once your exams are over, you can fully dedicate yourself to the project. If you have any specific concerns or requirements regarding your schedule, feel free to communicate them with the project team. Good luck with your exams, and I look forward to your contributions in June!
