### ISSUE TITLE
Add Icons

### ISSUE THREAD

**Issue by sailaja-adapa** [Counselllor/Counsellor-Web#704]
Hello Project Admin
I would like to add Icons to Navbar and Footer 
Can you Assign me this Issue Under GSSOC'24 @thestarsahil 

![tt](https://github.com/Counselllor/Counsellor-Web/assets/161804629/f06686ee-5043-48b8-9bdb-311777645737)
![ttt](https://github.com/Counselllor/Counsellor-Web/assets/161804629/3ca50383-b47c-47f2-bf82-0ec96db11c4c)

**Comment by thestarsahil** [comment]
Good to Go ! Make Sure icon shoudl be small in size and consists of same theme color 
Drop your Disord ID here , Connect with other peers contributors in a group !
Welcome to Open source !

**Comment by thestarsahil** [comment]
Mostly PR merged , due to repeatedly contribution in this organisation !
So make sure to raise Issues more as possible that consisting of level3 contain !

**Comment by sailaja-adapa** [comment]
Yeah okk @thestarsahil Thank you 
 my discord I'd : sailajaadapa_777

**Comment by sailaja-adapa** [comment]
> Mostly PR merged , due to repeatedly contribution in this organisation ! So make sure to raise Issues more as possible that consisting of level3 contain !

Yeah okkk @thestarsahil

**Comment by thestarsahil** [comment]
Did you joined the GSSOC'24 in discord ?

**Comment by sailaja-adapa** [comment]
No @thestarsahil

**Comment by thestarsahil** [comment]
https://discord.com/channels/1231112132595028008/1239913420749410335
try to join this

**Comment by sailaja-adapa** [comment]
Yeah okk @thestarsahil
