### ISSUE TITLE
Missing git pull command in contributing.md file 

### ISSUE THREAD

**Issue by Amruta7203** [Counselllor/Counsellor-Web#709]
**Describe the bug**
git pull upstream main command is missing in the contributing.md file which is very important to execute before making any changes. This ensures that the changes are being made to the updated code.

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/Counselllor/Counsellor-Web/assets/116087736/414ddc40-85b8-4124-8ff8-fc29898b99cd)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masterboy376** [comment]
Hello @thestarsahil I would like to work on this issue under gssoc'24.

**Comment by thestarsahil** [comment]
> Hello @thestarsahil I would like to work on this issue under gssoc'24.

You can't even make conflict on other , issue if you want to contribute just raise Issues and PR

**Comment by thestarsahil** [comment]
As our assigning only level 3 Issues and PR but i request to raise issue which containing level 3 and for minor changes you can work further after merging more and more PR

**Comment by thestarsahil** [comment]
@Amruta7203 Drop your discord Id
