### ISSUE TITLE
Automatic Year Update in Footer Copyright Section

### ISSUE THREAD

**Issue by Amruta7203** [Counselllor/Counsellor-Web#710]
**Is your feature request related to a problem? Please describe.**
This issue proposes implementing a solution to automatically update the current year in the footer copyright section. 
Currently, the year is likely hardcoded, requiring manual updates each year.

The footer shows 2023 year currently:
![image](https://github.com/Counselllor/Counsellor-Web/assets/116087736/ceed2f8f-566a-466a-bb56-3793f56aa955)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masterboy376** [comment]
Hello @thestarsahil I would like to work on this issue under gssoc'24.
