### ISSUE TITLE
content overlapping navbar 

### ISSUE THREAD

**Issue by Amruta7203** [Counselllor/Counsellor-Web#711]
**Describe the bug**
The content is overlapping the navbar in About us page 

**To Reproduce**

**Expected behavior**

**Screenshots**

![image](https://github.com/Counselllor/Counsellor-Web/assets/116087736/2688d799-44b1-4c58-adf7-df7acdaaf64c)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by masterboy376** [comment]
Hello @thestarsahil I would like to work on this issue under gssoc'24.
