### ISSUE TITLE
Adding tailwind

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#718]
**Is your feature request related to a problem? Please describe.**
I want to first try to replace the css by tailwind

**Comment by ayush-848** [comment]
@thestarsahil Do you agree with this?? about moving it to tailwind slowly

**Comment by avinash-24-aptrix** [comment]
please can you specify more ? please

**Comment by ayush-848** [comment]
> please can you specify more ? please

well replacing the css codes with tailwind. of course not all of them together.

**Comment by avinash-24-aptrix** [comment]
ok then i will contribute

**Comment by ayush-848** [comment]
> ok then i will contribute

Actually I have raised the issue to contribute myself.

Why not you create another page with tailwind ??

**Comment by avinash-24-aptrix** [comment]
ok then i am converting forgot password page first .

**Comment by ayush-848** [comment]
> ok then i am converting forgot password page first .

Yaa create a separate issue, and request @thestarsahil to assign you

**Comment by avinash-24-aptrix** [comment]
ok

**Comment by thestarsahil** [comment]
@ayush-848 Good to Go !

**Comment by ayush-848** [comment]
@thestarsahil Since this is creating problems, why not I just add tailwind and its configuration, what do you say???

**Comment by ayush-848** [comment]
@thestarsahil Since this is creating problems, why not I just add tailwind and its configuration, what do you say???
