### ISSUE TITLE
We need to refactor the existing CSS to utilize Tailwind CSS. This transition aims to streamline our styling process, enhance consistency, and make our codebase easier to maintain and scale.

### ISSUE THREAD

**Issue by ghost** [Counselllor/Counsellor-Web#728]
### Why Convert to Tailwind CSS?

- **Utility-First Framework**: Tailwind CSS uses utility classes to build designs directly in the markup, reducing the need for extensive custom CSS.
- **Efficient Development**: Tailwind's approach speeds up the styling process by allowing developers to apply styles directly in the HTML.
- **Maintainability**: Using Tailwind's utility classes makes our CSS more manageable and helps avoid specificity issues common with custom styles.
- **Customization and Theming**: Tailwind is highly customizable, enabling us to easily adjust themes and design tokens as our project evolves.
- **Responsive Design**: Tailwind simplifies the creation of responsive layouts with its pre-configured responsive utilities, removing the need for custom media queries.

By adopting Tailwind CSS, we can enhance our development workflow and maintain a cleaner and more adaptable codebase.

## Tasks

1. **Set Up Tailwind CSS**
   - Install and configure Tailwind CSS in the project.
   - Ensure all required dependencies are included.

2. **Refactor Styles**
   - Convert existing CSS to Tailwind utility classes.
   - Replace custom styles with appropriate Tailwind classes while maintaining the original design integrity.

3. **Maintain Design Consistency**
   - Check that the overall look and feel remain consistent post-transition.
   - Adjust any discrepancies to match the original design closely.

4. **Update Documentation**
   - Update any relevant documentation to reflect the use of Tailwind CSS.
   - Provide guidance on how to use Tailwind for future development.

5. **Testing**
   - Test the updated styles across various browsers and devices to ensure compatibility and responsiveness.

### References

- [Tailwind CSS Documentation](https://tailwindcss.com/docs)
- [Migration Guide to Tailwind](https://tailwindcss.com/docs/migration)

**Comment by thestarsahil** [comment]
Good to Go !
As you know we are accepting more PR as contributors repeatedly contribute to this org

**Comment by avinash-24-aptrix** [comment]
> Good to Go !
> As you know we are accepting more PR as contributors repeatedly contribute to this org

so I will be converting the website to Tailwind CSS, and I'll do this page by page to ensure a smooth transition. After each page is converted, I'll create a pull request for review.

If you have any priorities or insights, please share them. Your feedback is valuable as we work through this update!

**Comment by thestarsahil** [comment]
@avinash-24-aptrix Go with that ! I'll Update rest after

**Comment by avinash-24-aptrix** [comment]
ok first page coming soon stay updated ☻☻

**Comment by Soumya880** [comment]
I want to work on it, Can you assign it to me?

**Comment by thestarsahil** [comment]
@Soumya880 Make a new issue with details 
which portion you want to work on css
