### ISSUE TITLE
Year needs to update dynamically in footer

### ISSUE THREAD

**Issue by kapilG0** [Counselllor/Counsellor-Web#730]
**Describe the bug**
Year needs to be update dynamically in footer

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/59639410/47948274-d9cf-4087-b6cb-8b3cc931198a)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by kapilG0** [comment]
Hello @thestarsahil please assign this issue to me under gssoc 24

**Comment by thestarsahil** [comment]
Thanks, As we accepting major 3 level of problem , and this is one of them 
We request to contribute as much as possible with containing level 3

**Comment by kapilG0** [comment]
Hello @thestarsahil here is pr https://github.com/Counselllor/Counsellor-Web/pull/748 for this issue please check
