### ISSUE TITLE
Quality icons

### ISSUE THREAD

**Issue by AkhilaSunesh** [Counselllor/Counsellor-Web#744]
**Describe the bug**
![image](https://github.com/Counselllor/Counsellor-Web/assets/140897461/8ad40a0e-1fc3-4265-979b-63697ddbae08)
The icons are blurred in the Contacts page

**Expected behavior**
Better outlook of the website

**Additional context**
Kindly assign me this issue.

**Comment by RamakrushnaBiswal** [comment]
hi @thestarsahil can i work on it i can complete it with in one day
