### ISSUE TITLE
Improve the testimonials page

### ISSUE THREAD

**Issue by AkhilaSunesh** [Counselllor/Counsellor-Web#746]
**Describe the bug**
![image](https://github.com/Counselllor/Counsellor-Web/assets/140897461/f0939311-7865-4a56-8cca-c02ee81309f2)
Add valid content.
To make it authentic

**Additional context**
Kindly assign me this issue

**Comment by RamakrushnaBiswal** [comment]
hi @thestarsahil can i work upon the issue under gssoc

**Comment by thestarsahil** [comment]
@AkhilaSunesh are you working !

**Comment by AkhilaSunesh** [comment]
Yes I am...I will finish it today
