### ISSUE TITLE
Add error 404 page

### ISSUE THREAD

**Issue by VC6378** [Counselllor/Counsellor-Web#75]
Hey,
I want to add an error 404 page to the website.
Thanks and Regards,
Vibhuti Chandrakar.

**Comment by thestarsahil** [comment]
Hello @VC6378 

Thank you for your interest in adding an error 404 page to the website. An error 404 page is a valuable addition as it helps users navigate smoothly when they encounter a page that cannot be found.

I appreciate your willingness to contribute to the project. I will assign the task to you under GSSOC 2023. You can proceed with designing and implementing the error 404 page. Feel free to reach out if you have any questions or need assistance during the process.

**Comment by VC6378** [comment]
@thestarsahil Thank you sir for giving me this opportunity.

**Comment by thestarsahil** [comment]
Completed
