### ISSUE TITLE
Edit deleted NavBar styles

### ISSUE THREAD

**Issue by sau-mili** [Counselllor/Counsellor-Web#783]
**Describe the bug**
I see the navbar styles are altered in an unfitted manner. 
I wish to change those and fix it.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by sau-mili** [comment]
can you help me? getting error 
![Screenshot 2024-06-27 222516](https://github.com/Counselllor/Counsellor-Web/assets/146661411/a2faf29d-1aff-47c0-b5c5-a8e3332b02fe)

**Comment by sau-mili** [comment]
https://github.com/Counselllor/Counsellor-Web/assets/146661411/fdcfafa6-62f4-4489-a8ba-438413e6221b

Is this okay? Please check

**Comment by thestarsahil** [comment]
Okay Raise PR !

**Comment by sau-mili** [comment]
Some recent push is causing my CSS additions overwrite. I am trying to figure out the issue. Hope it gets solved soon

**Comment by sau-mili** [comment]
Should revert back the commits, and then push the changes? it will only change Navbar component folder

**Comment by sau-mili** [comment]
When i am going back to that old commit, the navbar is working fine, but pulling new changes causing something, that I am unable to figure out

**Comment by thestarsahil** [comment]
fork a new project and try to do from scratch , let's try this !
Delete the old ones

**Comment by sau-mili** [comment]
Tried it, same issue.

**Comment by thestarsahil** [comment]
Can you send the whole code here !
let me check from side

**Comment by sau-mili** [comment]
Missed deadline IG
