### ISSUE TITLE
Typewriter effect in the Home Section

### ISSUE THREAD

**Issue by Damini2004** [Counselllor/Counsellor-Web#792]
**Is your feature request related to a problem? Please describe.**
It will add typewiter effect to the text for tempting effect.
**Describe the solution you'd like**
It will help to grab more user attention 
**Describe alternatives you've considered**
This will enhance user engagement and attention.
**Additional context**
![image](https://github.com/Counselllor/Counsellor-Web/assets/119414762/f5ac4f12-b0eb-4eb2-a18d-6fd86cc1cc18)

**Comment by thestarsahil** [comment]
We are not looking for this , you can try with college cards responsive 
Thanks !
