### ISSUE TITLE
Enhance : Ui of the Signup page

### ISSUE THREAD

**Issue by Pragati-3003** [Counselllor/Counsellor-Web#8]
I would like to change the ui of the Signup page to make it more attactive by adding some backgrounds ,hover effects.
![coun1](https://github.com/thestarsahil/Counsellor/assets/132778037/4362ef6c-2338-48f4-94d7-2151a3c89f39)

So , please assign this issue to me.

**Comment by thestarsahil** [comment]
That's great @Pragati-3003 ! I appreciate your enthusiasm to contribute to the project. Adding backgrounds and hover effects to the Signup page to make it more attractive sounds like an excellent idea. To proceed with this task, please create a design or mockup showcasing the changes you would like to make. Once you have the design ready, kindly share it with us. We can then discuss the implementation details and assign the task to you. Thank you for your interest and contribution!

**Comment by Pragati-3003** [comment]
> > That's great @Pragati-3003 ! I appreciate your enthusiasm to contribute to the project. Adding backgrounds and hover effects to the Signup page to make it more attractive sounds like an excellent idea. To proceed with this task, please create a design or mockup showcasing the changes you would like to make. Once you have the design ready, kindly share it with us. We can then discuss the implementation details and assign the task to you. Thank you for your interest and contribution!
> 
> Okie , I'll share screenshots when the design will ready.
![IMG_20230530_150706](https://github.com/thestarsahil/Counsellor/assets/132778037/0db016f7-2dff-46f8-97d5-ba7a3441cef1)

This is the sample design, if you wanna any other changes than please inform me.

**Comment by thestarsahil** [comment]
Check out the New Redesigned on Readme file 
Thanks  You !

**Comment by thestarsahil** [comment]
@Pragati-3003 Do yo want to work on any issue right now ?
