### ISSUE TITLE
Implement "Back To Home Button"

### ISSUE THREAD

**Issue by MastanSayyad** [Counselllor/Counsellor-Web#802]
Hey @thestarsahil 

I would like to Design and implement "Back To Home" Button 

**Like this**

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/86372733-d5bf-45d6-b92b-73983c56e60d)

In Following Pages:

-  **Missing pages** Such as in **Blogs and Our Contributors Page** 

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/914b3263-ee95-4bbb-88d2-9853f054b5e9)

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/98ff0e85-2ff8-476a-b274-638b0d534d2b)

- Enhance Back to home in **Blog, Help, Privacy, Terms** Pages so that the users can navigate back to the Home Page

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/c83b5a23-2fc3-4ce4-85e3-3ba758f587f5)

**Comment by MastanSayyad** [comment]
@thestarsahil could you pls assign this issue to me under GSSOC

**Comment by thestarsahil** [comment]
Make sure , Raise more PR as possible !

**Comment by MastanSayyad** [comment]
> Make sure , Raise more PR as possible !

I didn't get it by raise more PR as possible part?
