### ISSUE TITLE
[Enhancement] : Image background `transparent`

### ISSUE THREAD

**Issue by sivaprasath2004** [Counselllor/Counsellor-Web#804]
- In this project `Login` screen image change to the background trnasparent format , because in `Dark` mode cannot good that image .
- if i want to change transparent image.
- please assign me..

### Screen Shot

![Screenshot from 2024-06-30 17-50-26](https://github.com/Counselllor/Counsellor-Web/assets/121082414/138b231d-8c36-40d2-9e20-3ac5086b4247)

**Comment by thestarsahil** [comment]
Good to go !
Make sure to majorly here are repeatedly contributors PR merges which containing level 3 
Welcome
