### ISSUE TITLE
Creating dynamically using local storage,the profile and profile edits part

### ISSUE THREAD

**Issue by ayush-848** [Counselllor/Counsellor-Web#816]
**Is your feature request related to a problem? Please describe.**
I want to create the profile part to show the user name, etc.

**Comment by ayush-848** [comment]
@thestarsahil please you add the tailwind config, and let me know

**Comment by ayush-848** [comment]
@thestarsahil 
![image](https://github.com/Counselllor/Counsellor-Web/assets/126975547/5d3d1fa9-6574-4ffc-9ed6-28e890546469)
I have already made a couple of changes.

I would request you to not merge any profile changes

**Comment by thestarsahil** [comment]
Okay Raise PR
