### ISSUE TITLE
[Bug] : Text cannot visible

### ISSUE THREAD

**Issue by sivaprasath2004** [Counselllor/Counsellor-Web#819]
**Describe the bug** 

- `dashboard` page I will search `Ann` the result can be showed `Anna University` place `Tamil Nadu` cannot  be proper  `Tamil` word can be hided

**To Reproduce**
1. Go to `/dashboard`
2. Click on `search`
3. See error
 
**Screenshots** 

![Screenshot from 2024-07-02 09-22-09](https://github.com/Counselllor/Counsellor-Web/assets/121082414/ea5ef406-a23b-40c7-800b-2564e97852b7)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser :chrome 

**Smartphone (please complete the following information):**
 - Device: Realme 8
 - OS:  Android
 - Browser : chrome 

**Additional context**

**Comment by thestarsahil** [comment]
Using a dynamically function upgrading size of card for every card that should reflect on single particular college card !
