### ISSUE TITLE
Available course enhancement

### ISSUE THREAD

**Issue by Damini2004** [Counselllor/Counsellor-Web#831]
**Is your feature request related to a problem? Please describe.**
Adding more hover effect
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/Counselllor/Counsellor-Web/assets/119414762/0df441e6-7a5c-4be2-bf0c-f003752f3376)

**Comment by thestarsahil** [comment]
Its Done
