### ISSUE TITLE
Feat: Make the Dashboard properly responsive for mobile and tablet screens

### ISSUE THREAD

**Issue by Asymtode712** [Counselllor/Counsellor-Web#846]
**Is your feature request related to a problem? Please describe.**
Currently, the website's dashboard college cards are not properly responsive for mobile and tablet screens

**Describe the solution you'd like**
I would like to add responsiveness to these cards with the help of media queries

**Additional context**

https://github.com/Counselllor/Counsellor-Web/assets/115717746/32f39514-bc85-4ec8-bb56-fc4ca2795103

**Comment by Asymtode712** [comment]
@thestarsahil Please assign me this issue

**Comment by thestarsahil** [comment]
Okay , we are majorly working with repeatedlty contributors , Make sure to raise PR as possible !
