### ISSUE TITLE
To enhance the Career page 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#851]
**Is your feature request related to a problem? Please describe.**
I want to enhance the Career page by doing following changes : -
1. Adding fade up animation
2. Implementing dark mode for the website
3. Adding navbar to it 
4. Fix email field in career advice 
5. Enhance the button on hovering 
6.  Increase some size of the text written 

**Describe the solution you'd like**
I want to do all these changes 

https://github.com/Counselllor/Counsellor-Web/assets/118350936/5476f9ae-675f-4eaa-b406-ab6cc2c3863c

![Screenshot 2024-07-03 214324](https://github.com/Counselllor/Counsellor-Web/assets/118350936/12314b53-0329-420e-b132-2dd691f1cb24)

**Comment by thestarsahil** [comment]
We want simple as possible !
