### ISSUE TITLE
navbar and footer missing in this page 

### ISSUE THREAD

**Issue by komal-agarwal5** [Counselllor/Counsellor-Web#866]
**Describe the bug**
navbar and footer missing in career support page,it is difficult for user to go back to home page or any other page.
Hence I want to add this.
**To Reproduce**
1. Go to website
2. Click on Career support

**Expected behavior**

**Screenshots**
![Screenshot 2024-07-04 144352](https://github.com/Counselllor/Counsellor-Web/assets/122633300/c566fdeb-5134-4819-bd21-92f562295bfe)
![Screenshot 2024-07-04 144402](https://github.com/Counselllor/Counsellor-Web/assets/122633300/83d1c8ff-43ef-4c1f-93a8-7d2631a674c7)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by thestarsahil** [comment]
Navbar is done 
Add Footer
