### ISSUE TITLE
BUG: The Dark Mode Resets After Refreshing

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [Counselllor/Counsellor-Web#867]
Hey @thestarsahil 

In this website the dark mode is not working after refreshing the page.

https://github.com/Counselllor/Counsellor-Web/assets/163530398/42a63719-157d-40ad-8976-093d691410a4

Could you please assign this issue to me under GSSOC24 ?

**Comment by thestarsahil** [comment]
Make Sure to contribute repeatedly !
