### ISSUE TITLE
[Feature] : Contact Us page `Mail` Announce

### ISSUE THREAD

**Issue by sivaprasath2004** [Counselllor/Counsellor-Web#872]
- In this project `mail` announce like contact us form was filled after the user can sent `click` then backend `nodemailer` can be  announce user mail address `Thank you for Contacting` message user mail addresses.

### Screen Shots

![Screenshot from 2024-07-05 07-11-05](https://github.com/Counselllor/Counsellor-Web/assets/121082414/3eaea6ea-4ddd-4704-a9be-4d8246be753b)

- Like this 

![Screenshot from 2024-07-05 07-16-16](https://github.com/Counselllor/Counsellor-Web/assets/121082414/a2b8e82d-8573-40f8-9f23-9691d55f5708)

**Comment by thestarsahil** [comment]
Its already done working on it , look into another problem statement
