### ISSUE TITLE
Adding a dark mode in website

### ISSUE THREAD

**Issue by Shrejal123** [Counselllor/Counsellor-Web#89]
I wants to work on this issue . Please assign this issue under gssoc23.

**Comment by thestarsahil** [comment]
We would like to express our gratitude for your contributions and hard work towards the project. Your dedication and efforts have been greatly appreciated.

However, we wanted to inform you that we have recently undergone a complete redesign of the website's structure. As a result, we kindly request you to review the updated README file to ensure that your contributions align with the new structure and guidelines.
If you have any questions or need further clarification, please don't hesitate to reach out to us. We are here to support you throughout the process and assist with any challenges you may encounter.

Once again, thank you for your commitment and valuable contributions. We look forward to your continued involvement in the project.

Make Sure to join Discord Server For latest updates
