### ISSUE TITLE
 Want to create the login page like in readme file 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#901]
**Is your feature request related to a problem? Please describe.**
I want to re-cerate or change the designing of the login page as given in the readme  file

![Screenshot 2024-07-06 231224](https://github.com/Counselllor/Counsellor-Web/assets/118350936/a459015d-8164-4f0d-b301-885bf3497c22)

**Comment by thestarsahil** [comment]
Its already been done no need to work on
