### ISSUE TITLE
The navbar links from the carrer support are not clickable 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#903]
**Is your feature request related to a problem? Please describe.**
When i am clicking on any link the link is not clickable lie it is not routing to any url anymore 

https://github.com/Counselllor/Counsellor-Web/assets/118350936/f08339cf-b910-4aef-a639-30e5a4e9d721

**Comment by thestarsahil** [comment]
the navabar of carrier page is not same as dashboard navabar work on that also
![Screenshot from 2024-07-07 20-31-49](https://github.com/Counselllor/Counsellor-Web/assets/84167034/82ac7228-d7bc-4552-b5b0-25455ff20056)
