### ISSUE TITLE
Want to Add Blog Page

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#909]
We need to add a new Blog Page to this website. This page will display a list of blog posts with titles, excerpts, and publication dates. Each blog post should be clickable, leading to a detailed view of the post. The design will be clean, responsive, and consistent with the overall site aesthetics.

**Comment by thestarsahil** [comment]
Want to do dynamic

**Comment by nishant0708** [comment]
Hey @thestarsahil Actually there is a  problem whenever user login /signup his information is not getting stored in realtime database it is just getting authenticated so i am raising new issue for that after that only i could make this page .

**Comment by thestarsahil** [comment]
@nishant0708 ok
