### ISSUE TITLE
Contact Section Updation

### ISSUE THREAD

**Issue by Damini2004** [Counselllor/Counsellor-Web#923]
**Is your feature request related to a problem? Please describe.**
Updating the UI

**Describe the solution you'd like**
Updating the UI

**Describe alternatives you've considered**
Updating the UI

**Additional context**
![image](https://github.com/Counselllor/Counsellor-Web/assets/119414762/c2a08617-5128-4dc7-9e5f-416d69cf2aa8)

**Comment by thestarsahil** [comment]
Already working
