### ISSUE TITLE
Help Page integration

### ISSUE THREAD

**Issue by Damini2004** [Counselllor/Counsellor-Web#925]
**Is your feature request related to a problem? Please describe.**
If anyone wanted help it will shown
**Describe the solution you'd like**
If anyone wanted help it will shown

**Describe alternatives you've considered**
If anyone wanted help it will shown

**Additional context**
![image](https://github.com/Counselllor/Counsellor-Web/assets/119414762/ce5e3b2d-ae1b-48a8-a549-69fc13b26d29)

**Comment by thestarsahil** [comment]
I want to same pattern of contribution page styling 
Can you able to make that ?

**Comment by Damini2004** [comment]
@thestarsahil  Yes i can do it 
Firstly i will resolve this help page styling then i will create new issue for above thing.
