### ISSUE TITLE
"UI Enhancements" and Add "More QnA's to FAQ Section in Dashbaord

### ISSUE THREAD

**Issue by MastanSayyad** [Counselllor/Counsellor-Web#928]
Hey @thestarsahil 

I would like to 

- make the enhancements in FAQ section to look more engaging and attractive 
- Add More questions that may help the users while using the website
- Make it responsive
- Match to the website design theme.
- Smooth and Visually appealing.

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/8e682b21-c21d-4300-a9ea-de2bf587aa55)

- I will also make it responsive and make proper alignments to ensure the clarity and accesibilty

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/4b8474c2-010e-477e-97ef-674d0b8e7a0c)

Could you please assign this issue to me, under GSSOC?

**Comment by thestarsahil** [comment]
Not require
