### ISSUE TITLE
In Dashboard College Cards Are Not Responsive 

### ISSUE THREAD

**Issue by MastanSayyad** [Counselllor/Counsellor-Web#929]
Hey @thestarsahil 

The College cards in Dashboard are not responsive at all, they are not perfectly align in mobile view 

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/939486c4-642a-4791-a825-b28d4d3c28c5)

![image](https://github.com/Counselllor/Counsellor-Web/assets/101971980/56c9fe62-136e-4c57-8e05-831ee6a3f71a)

Please assign this issue to me under GSSOC.

**Comment by MastanSayyad** [comment]
@thestarsahil Could you please assign this issue to me?

**Comment by thestarsahil** [comment]
Done
