### ISSUE TITLE
 Dashbord cards are not fully responsive 

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [Counselllor/Counsellor-Web#953]
**Describe the bug**
I saw that the dashboard cards are not fully responsive for some screen sizes 

**To Reproduce**
1. Go to dashboard

2. Small screen size 

**Expected behavior**
It must responsive 

**Screenshots**
![image](https://github.com/Counselllor/Counsellor-Web/assets/118350936/50cbf1ea-869f-4f4b-a17f-b3483b0ce0cd)

**Comment by thestarsahil** [comment]
It should be align center after smaling the size
