### ISSUE TITLE
Want to Write Backend Of Contact Page

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#980]
**Is your feature request related to a problem? Please describe.**
In This i want when user submits his message should get stored in realtime database In Queries Section

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/7b4b77d8-d816-4d19-b24f-230d88cc90a7)

**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
#960 can you please help me that he is working with that !

**Comment by nishant0708** [comment]
> #960 can you please help me that he is working with that !

Yaa let me check that code

**Comment by nishant0708** [comment]
hey @thestarsahil yaa i checked . Actually he has implemented that contact page mail service using Express which could easily be done by Emailjs or firebase services itself .

**Comment by nishant0708** [comment]
@thestarsahil  And it doesnt need any additional backend code so only merge that if he could make it work without Express server

**Comment by nishant0708** [comment]
hey @thestarsahil  Sir That Contributor is Enable To Do that Without Backend Can i Work On That Issue?

**Comment by nishant0708** [comment]
> hey @thestarsahil Sir That Contributor is Enable To Do that Without Backend Can i Work On That Issue?

hey @thestarsahil please assign this to me
