### ISSUE TITLE
Want to Add Sort Functionality in Search bar 

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#982]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
![image](https://github.com/user-attachments/assets/6373a129-265f-4d00-8cea-7ada00be9755)

**Describe alternatives you've considered**

**Additional context**

**Comment by thestarsahil** [comment]
Elaborate

**Comment by nishant0708** [comment]
Hey @thestarsahil we can feature where we can sort college on basis of CTC and filter like college above this CTC I should only see something like that

**Comment by thestarsahil** [comment]
Here use a only a filter option on side of search bar
