### ISSUE TITLE
Want to design DarkMode Ui of Career page 

### ISSUE THREAD

**Issue by nishant0708** [Counselllor/Counsellor-Web#983]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/user-attachments/assets/0faa05cb-39bf-40de-a26b-52ea037f353f)
Currently darkmode of this page is not working i want to Fix that

**Comment by thestarsahil** [comment]
Lets have a discuss this on discord vs ?

**Comment by nishant0708** [comment]
yaa okay @thestarsahil please give me your discord id my is niko7479

**Comment by thestarsahil** [comment]
Added , You can work on that now
